"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertCircle, ArrowLeft, CalendarClock, Check, Clock3, FileText, Info, Loader2, Save, Search, UserRound } from "lucide-react";
import { toast } from "sonner";
import { AdminFormCard, AdminFormField, adminControlClass, adminPrimaryButtonClass, adminSecondaryButtonClass } from "@/components/shared/admin-patterns";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PersonSearchSelector } from "@/components/shared/PersonSearchSelector";
import { CatalogDetailField, CatalogLoadingState } from "@/features/activity-catalogs/components/CatalogPrimitives";
import { listActivitySchedulesClient } from "@/features/activity-schedules/services/activity-schedules.service";
import type { ActivitySchedule } from "@/features/activity-schedules/types/activity-schedule.types";
import { listActivitySessionsClient } from "@/features/activity-sessions/services/activity-sessions.service";
import type { ActivitySession } from "@/features/activity-sessions/types/activity-session.types";
import { listActividadesClient } from "@/features/actividades/services/actividades.service";
import type { Actividad } from "@/features/actividades/types/actividad.types";
import { ActivityImagePreview } from "@/features/actividades/components/ActivityImagePreview";
import { axiosInstance } from "@/lib/axios";
import { createEnrollmentSchema } from "../schemas/enrollment.schema";
import { createEnrollmentClient, updateEnrollmentClient } from "../services/enrollments.service";
import type { Enrollment } from "../types/enrollment.types";

type Citizen = { id:string; userId:string; fullName:string; firstName:string|null; lastName:string|null; documentNumber:string|null; email:string; avatarUrl:string|null; identityPhotoUrl:string|null; phone:string|null; address:string|null; locality:string|null; province:string|null; postalCode:string|null; birthDate:string|null };
type CitizenSearch = { data:{ items:Citizen[]; meta:{total:number;page:number;pageSize:number;pageCount:number} } };
const searchCitizens=async(query:string)=>(await axiosInstance.get<CitizenSearch>("/enrollments/citizens",{params:{q:query,page:1}})).data.data.items;
const identifyCitizenQr=async(qrToken:string)=>(await axiosInstance.post<{data:Citizen}>("/enrollments/citizens",{qrToken})).data.data;
const MODES: Record<string,{label:string;description:string}> = {
  HORARIO_FIJO:{label:"Horario fijo",description:"Una sola inscripción incluye todos los días y horarios definidos para la actividad."},
  TURNO_RECURRENTE:{label:"Turno recurrente",description:"Elegí uno o varios turnos semanales; el lugar se conserva hasta la fecha indicada o la baja."},
  TURNO_PUNTUAL:{label:"Reserva puntual",description:"La inscripción corresponde únicamente a una clase o turno concreto."},
  ACCESO_LIBRE:{label:"Acceso libre",description:"No requiere inscripción previa: el ingreso se registra al presentarse."},
  EVENTO_UNICO:{label:"Evento único",description:"La inscripción reserva una única fecha del evento."},
  CURSO_PERIODO:{label:"Curso por período",description:"Una sola inscripción incluye el cronograma completo del curso."},
};
const dayOrder=["LUNES","MARTES","MIERCOLES","JUEVES","VIERNES","SABADO","DOMINGO"];
const dayLabels:Record<string,{short:string,label:string}>={LUNES:{short:"L",label:"Lun"},MARTES:{short:"M",label:"Mar"},MIERCOLES:{short:"X",label:"Mié"},JUEVES:{short:"J",label:"Jue"},VIERNES:{short:"V",label:"Vie"},SABADO:{short:"S",label:"Sáb"},DOMINGO:{short:"D",label:"Dom"}};

export function EnrollmentForm({ initialValues, onLoadingChange, backHref = "/enrollments" }:{initialValues?:Enrollment;onLoadingChange?:(loading:boolean)=>void;backHref?:string}) {
  const router=useRouter(), params=useSearchParams();
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[sessionsLoading,setSessionsLoading]=useState(false),[checkingActivityId,setCheckingActivityId]=useState<string|null>(null);
  const [activities,setActivities]=useState<Actividad[]>([]),[schedules,setSchedules]=useState<ActivitySchedule[]>([]),[sessions,setSessions]=useState<ActivitySession[]>([]);
  const [activityQuery,setActivityQuery]=useState(""),[selectedCitizen,setSelectedCitizen]=useState<Citizen|null>(initialValues?{id:initialValues.user.id,userId:"",fullName:[initialValues.user.firstName,initialValues.user.lastName].filter(Boolean).join(" "),firstName:initialValues.user.firstName,lastName:initialValues.user.lastName,documentNumber:initialValues.user.documentNumber,email:initialValues.user.email,avatarUrl:null,identityPhotoUrl:null,phone:null,address:null,locality:null,province:null,postalCode:null,birthDate:null}:null);
  const [availability,setAvailability]=useState<Array<{horarioActividadId:string;horaInicio:string;status:string;available:number}>>([]);
  const [activityConflict,setActivityConflict]=useState<{id:string;message:string}|null>(null),[slotConflict,setSlotConflict]=useState<{key:string;message:string}|null>(null);
  const [form,setForm]=useState({actividadId:initialValues?.activitySchedule.activity.id??"",horarioActividadIds:initialValues?.selectedSchedules.map(x=>x.id)??[],horariosSeleccionados:[] as Array<{horarioActividadId:string;horaInicio:string;horaFin:string}>,classId:"",fechaFin:"",observaciones:initialValues?.observations??""});

  useEffect(()=>{void Promise.all([listActividadesClient({estado:"ACTIVA"}),listActivitySchedulesClient({status:"ACTIVO"})]).then(([a,s])=>{setActivities(a);setSchedules(s);const requested=params.get("activityScheduleId");if(requested){const schedule=s.find(x=>x.id===requested);if(schedule)setForm(current=>({...current,actividadId:schedule.activityId,horarioActividadIds:[requested]}));}}).catch(()=>toast.error("No pudimos cargar las opciones.")) .finally(()=>setLoading(false));},[params]);
  useEffect(()=>onLoadingChange?.(loading),[loading,onLoadingChange]);

  const selectedActivity=activities.find(x=>x.id===form.actividadId), mode=selectedActivity?.modalidadOperacion;
  const activitySchedules=useMemo(()=>schedules.filter(x=>x.activityId===form.actividadId).sort((a,b)=>dayOrder.indexOf(a.day)-dayOrder.indexOf(b.day)||a.startTime.localeCompare(b.startTime)),[schedules,form.actividadId]);
  const selectedScheduleSummary=useMemo(()=>formatScheduleSummary(activitySchedules),[activitySchedules]);
  const recurringSlots=useMemo(()=>activitySchedules.flatMap(buildScheduleSlots),[activitySchedules]);
  useEffect(()=>{if(initialValues||!selectedActivity||!["TURNO_PUNTUAL","EVENTO_UNICO"].includes(selectedActivity.modalidadOperacion)){setSessions([]);return;}setSessionsLoading(true);void listActivitySessionsClient({activityId:selectedActivity.id,dateFrom:new Date().toISOString().slice(0,10),page:1,pageSize:100}).then(r=>setSessions(r.data.filter(x=>["PROGRAMADA","EN_CURSO"].includes(x.status)))).catch(()=>setSessions([])).finally(()=>setSessionsLoading(false));},[selectedActivity,initialValues]);

  async function selectActivity(id:string){const activity=activities.find(x=>x.id===id),scopedSchedules=schedules.filter(x=>x.activityId===id),scoped=scopedSchedules.map(x=>x.id);setActivityConflict(null);setSlotConflict(null);if(activity&&selectedCitizen&&["HORARIO_FIJO","CURSO_PERIODO"].includes(activity.modalidadOperacion)){setCheckingActivityId(id);try{await axiosInstance.post("/enrollments/availability",{usuarioId:selectedCitizen.id,actividadId:id,selections:scopedSchedules.map(item=>({horarioActividadId:item.id,horaInicio:item.startTime,horaFin:item.endTime}))});}catch(error:any){const message=error?.response?.data?.message??"La persona no está disponible para los horarios de esta actividad.";toast.error(message);setActivityConflict({id,message});setCheckingActivityId(null);return;}setCheckingActivityId(null);}setAvailability([]);setForm(current=>({...current,actividadId:id,classId:"",horariosSeleccionados:[],horarioActividadIds:activity&&["HORARIO_FIJO","CURSO_PERIODO"].includes(activity.modalidadOperacion)?scoped:[]}));}
  function toggleSchedule(id:string){setForm(current=>({...current,horarioActividadIds:current.horarioActividadIds.includes(id)?current.horarioActividadIds.filter(x=>x!==id):[...current.horarioActividadIds,id]}));}
  async function toggleSlot(slot:{horarioActividadId:string;horaInicio:string;horaFin:string}){const key=`${slot.horarioActividadId}-${slot.horaInicio}`,exists=form.horariosSeleccionados.some(item=>item.horarioActividadId===slot.horarioActividadId&&item.horaInicio===slot.horaInicio),next=exists?form.horariosSeleccionados.filter(item=>!(item.horarioActividadId===slot.horarioActividadId&&item.horaInicio===slot.horaInicio)):[...form.horariosSeleccionados,slot];setSlotConflict(null);if(!next.length){setForm(current=>({...current,horariosSeleccionados:[],horarioActividadIds:[]}));setAvailability([]);return;}try{const {data}=await axiosInstance.post<{data:typeof availability}>("/enrollments/availability",{selections:next,usuarioId:selectedCitizen?.id,actividadId:form.actividadId});setAvailability(data.data);setForm(current=>({...current,horariosSeleccionados:next,horarioActividadIds:[...new Set(next.map(item=>item.horarioActividadId))]}));}catch(error:any){const message=error?.response?.data?.message??"La persona ya tiene otra actividad en ese horario.";toast.error(message);setSlotConflict({key,message});}}

  async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);try{if(initialValues){await updateEnrollmentClient(initialValues.id,{observaciones:form.observaciones||null});toast.success("Inscripción actualizada.");}else{const parsed=createEnrollmentSchema.parse({usuarioId:selectedCitizen?.id,actividadId:form.actividadId,horarioActividadIds:form.horarioActividadIds,horariosSeleccionados:form.horariosSeleccionados.length?form.horariosSeleccionados:undefined,claseActividadId:form.classId||undefined,fechaFin:form.fechaFin||null,observaciones:form.observaciones||null});const saved=await createEnrollmentClient(parsed);toast.success(saved.status==="LISTA_ESPERA"?"La inscripción quedó en lista de espera.":saved.status==="PENDIENTE"?"La inscripción quedó pendiente de documentación.":"Inscripción administrativa confirmada.");}router.replace(backHref);}catch(error:any){toast.error(error?.response?.data?.message??error?.issues?.[0]?.message??"No pudimos guardar la inscripción.");}finally{setSaving(false);}}

  if(loading)return <div className="grid min-h-80 place-items-center"><CatalogLoadingState label="formulario de inscripción"/></div>;
  if(initialValues)return <form onSubmit={submit} className="space-y-6"><AdminFormCard title="Inscripción" description="La actividad y su alcance se conservan; podés actualizar la observación administrativa."><div className="grid gap-3 md:grid-cols-2"><CatalogDetailField icon={UserRound} label="Ciudadano">{selectedCitizen?.fullName}</CatalogDetailField><CatalogDetailField icon={CalendarClock} label="Actividad">{initialValues.activitySchedule.activity.name}</CatalogDetailField></div><AdminFormField label="Observaciones" icon={FileText} align="start"><Textarea className={`${adminControlClass} min-h-32 py-3`} value={form.observaciones} onChange={e=>setForm(c=>({...c,observaciones:e.target.value}))}/></AdminFormField></AdminFormCard><Actions saving={saving} backHref={backHref}/></form>;

  const unavailable=mode==="ACCESO_LIBRE";
  const validScope=!!selectedCitizen&&!!selectedActivity&&!unavailable&&(["HORARIO_FIJO","CURSO_PERIODO"].includes(mode??"")?activitySchedules.length>0:mode==="TURNO_RECURRENTE"?form.horariosSeleccionados.length>0:!!form.classId);
  const filteredActivities=activityQuery.trim().length>=2?activities.filter(item=>item.id!==form.actividadId&&`${item.nombre} ${item.categoriaActividad?.nombre??item.categoria}`.toLowerCase().includes(activityQuery.trim().toLowerCase())):[];
  return <form onSubmit={submit} className="space-y-6">
    <AdminFormCard title="Ciudadano" description="Buscá por nombre, apellido o DNI; también podés identificar su credencial QR.">
      <PersonSearchSelector value={selectedCitizen} onChange={(person)=>{setSelectedCitizen(person);setActivityConflict(null);setSlotConflict(null);}} search={searchCitizens} identifyQr={identifyCitizenQr} title="Buscar ciudadano" />
    </AdminFormCard>
    <AdminFormCard title="Actividad" description="Buscá por nombre o categoría; los resultados aparecerán a partir de dos caracteres.">
      <AdminFormField label="Buscar actividad" icon={Search}><Input className={adminControlClass} value={activityQuery} onChange={event=>setActivityQuery(event.target.value)} placeholder="Nombre o categoría de la actividad"/></AdminFormField>
      {selectedActivity ? <div className="mt-4 flex items-start gap-4 rounded-2xl border border-[var(--brand-primary)] bg-[var(--brand-control)] p-4"><ActivityImagePreview source={selectedActivity.imagenUrl} alt={`Imagen de ${selectedActivity.nombre}`} className="h-20 w-24 shrink-0 rounded-2xl"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-extrabold text-[var(--brand-primary)]">{selectedActivity.nombre}</h3><span className="rounded-full border border-[var(--brand-secondary)]/40 bg-white px-2.5 py-1 text-xs font-bold text-[var(--brand-primary)]">{MODES[selectedActivity.modalidadOperacion]?.label}</span></div><p className="mt-1 line-clamp-2 text-sm text-[var(--brand-text)]">{selectedActivity.descripcionCorta || selectedActivity.descripcion || "Sin descripción informada."}</p><p className="mt-2 text-xs font-medium text-[var(--brand-muted)]">{selectedActivity.categoriaActividad?.nombre ?? selectedActivity.categoria} · {selectedActivity.establecimiento.nombre}</p><p className="mt-2 flex items-start gap-1.5 text-sm font-bold text-[var(--brand-primary)]"><CalendarClock className="mt-0.5 size-4 shrink-0 text-[var(--brand-secondary)]"/><span>{selectedScheduleSummary}</span></p></div></div> : null}
      <div className="mt-4 grid gap-2 md:grid-cols-2">{filteredActivities.map(a=>{const summary=formatScheduleSummary(schedules.filter(schedule=>schedule.activityId===a.id)),checking=checkingActivityId===a.id,conflict=activityConflict?.id===a.id;return <button type="button" key={a.id} disabled={checkingActivityId!==null} onClick={()=>void selectActivity(a.id)} className={`flex items-center gap-3 rounded-2xl border p-3 text-left disabled:opacity-70 ${conflict?"border-red-500 bg-red-50 ring-1 ring-red-200":form.actividadId===a.id?"border-[var(--brand-secondary)] bg-[var(--brand-control)]":"border-[var(--brand-border-soft)] bg-white"}`}><ActivityImagePreview source={a.imagenUrl} alt="" className="size-14 shrink-0 rounded-xl"/><span className="min-w-0 flex-1"><strong className={`block truncate ${conflict?"text-red-800":"text-[var(--brand-primary)]"}`}>{a.nombre}</strong><span className="block text-xs text-[var(--brand-muted)]">{MODES[a.modalidadOperacion]?.label} · {a.establecimiento.nombre}</span><span className="mt-1 flex items-start gap-1 text-xs font-bold text-[var(--brand-primary)]"><CalendarClock className="mt-px size-3.5 shrink-0 text-[var(--brand-secondary)]"/><span className="line-clamp-2">{checking?"Verificando disponibilidad...":summary}</span></span>{conflict?<span className="mt-2 flex items-start gap-1.5 text-xs font-bold leading-relaxed text-red-700"><AlertCircle className="mt-px size-4 shrink-0"/>{activityConflict.message}</span>:null}</span>{checking?<Loader2 className="ml-auto size-5 shrink-0 animate-spin text-[var(--brand-secondary)]"/>:conflict?<AlertCircle className="ml-auto size-5 shrink-0 text-red-600"/>:form.actividadId===a.id?<Check className="ml-auto size-5 shrink-0 text-[var(--brand-secondary)]"/>:null}</button>})}</div>
      {activityQuery.trim().length<2?<p className="mt-3 text-sm text-[var(--brand-muted)]">Ingresá al menos dos caracteres para buscar.</p>:null}
    </AdminFormCard>
    {selectedActivity?<AdminFormCard title={MODES[mode!]?.label??"Alcance"} description={MODES[mode!]?.description??"Definí el alcance de la inscripción."}>
      {unavailable?<div className="flex gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><Info className="shrink-0"/>Esta actividad es de acceso libre y no genera una inscripción previa. El ingreso se registra cuando la persona se presenta.</div>:null}
      {["HORARIO_FIJO","CURSO_PERIODO"].includes(mode!)?<div className="grid gap-2 md:grid-cols-2">{activitySchedules.map(s=><div key={s.id} className="rounded-xl border border-[var(--brand-secondary)] bg-[var(--brand-control)] p-4"><strong className="block text-[var(--brand-primary)]">{s.day} · {s.startTime} a {s.endTime}</strong><small>{s.establishment.name} · cupo {s.maxCapacity}</small></div>)}</div>:null}
      {mode==="TURNO_RECURRENTE"?<div className="grid gap-5">
        <div className="rounded-2xl border border-[var(--brand-border)] bg-[var(--brand-control)] p-4"><div className="mb-4 flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--brand-border-soft)] text-[var(--brand-primary)]"><CalendarClock className="size-5"/></span><div><h3 className="font-extrabold text-[var(--brand-primary)]">Días de la actividad</h3><p className="text-sm text-[var(--brand-muted)]">Elegí los días y horarios semanales que reservará la persona.</p></div></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{dayOrder.map(day=>{const available=activitySchedules.some(schedule=>schedule.day===day);const selected=form.horariosSeleccionados.some(slot=>activitySchedules.some(schedule=>schedule.id===slot.horarioActividadId&&schedule.day===day));const labels=dayLabels[day];return <div key={day} className={`grid min-h-16 place-items-center rounded-xl border text-center ${selected?"border-[var(--brand-primary)] bg-[#DDEF8F]":"border-[var(--brand-border)] bg-white"} ${available?"":"opacity-40"}`}><span><strong className="block text-[var(--brand-primary)]">{labels.short}</strong><small className="font-bold uppercase text-[var(--brand-muted)]">{labels.label}</small></span></div>})}</div></div>
        {dayOrder.map(day=>{const slots=recurringSlots.filter(slot=>slot.day===day);if(!slots.length)return null;return <section key={day} className="rounded-2xl border border-[var(--brand-border-soft)] bg-white p-4"><div className="mb-3 flex items-center gap-2"><Clock3 className="size-5 text-[var(--brand-secondary)]"/><h4 className="font-extrabold text-[var(--brand-primary)]">{dayLabels[day].label}</h4></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{slots.map(slot=>{const key=`${slot.horarioActividadId}-${slot.horaInicio}`,checked=form.horariosSeleccionados.some(item=>item.horarioActividadId===slot.horarioActividadId&&item.horaInicio===slot.horaInicio),cap=availability.find(item=>item.horarioActividadId===slot.horarioActividadId&&item.horaInicio===slot.horaInicio),conflict=slotConflict?.key===key;return <label key={key} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 transition ${conflict?"border-red-500 bg-red-50 ring-1 ring-red-200":checked?"border-[var(--brand-primary)] bg-[var(--brand-control)]":"border-[var(--brand-border-soft)] hover:border-[var(--brand-secondary)]"}`}><Checkbox checked={checked} onCheckedChange={()=>void toggleSlot(slot)} className="mt-1"/><span><strong className={`block ${conflict?"text-red-800":"text-[var(--brand-primary)]"}`}>{slot.horaInicio} a {slot.horaFin}</strong><small className="block text-[var(--brand-muted)]">Duración {toMinutes(slot.horaFin)-toMinutes(slot.horaInicio)} min · {slot.establishment}</small>{conflict?<small className="mt-2 flex items-start gap-1.5 font-bold leading-relaxed text-red-700"><AlertCircle className="mt-px size-4 shrink-0"/>{slotConflict.message}</small>:<small className={`mt-1 block font-bold ${cap?.status==="SIN_CUPO"?"text-red-700":"text-[var(--brand-secondary)]"}`}>{cap?cap.status==="DISPONIBLE"?`${cap.available} lugares disponibles`:cap.status==="LISTA_ESPERA"?"Sin cupo · pasa a espera":"Sin cupo":"Marcá para verificar disponibilidad"}</small>}</span></label>})}</div></section>})}
      </div>:null}
      {["TURNO_PUNTUAL","EVENTO_UNICO"].includes(mode!)?<div className="grid gap-2 md:grid-cols-2">{sessionsLoading?<CatalogLoadingState label="clases disponibles"/>:sessions.map(s=><button type="button" key={s.id} onClick={()=>setForm(c=>({...c,classId:s.id,horarioActividadIds:[s.activitySchedule.id]}))} className={`rounded-xl border p-4 text-left ${form.classId===s.id?"border-[var(--brand-secondary)] bg-[var(--brand-control)]":"border-[var(--brand-border-soft)] bg-white"}`}><strong className="block text-[var(--brand-primary)]">{s.date} · {s.startTime} a {s.endTime}</strong><small>{s.establishment.name} · {s.enrollmentSummary.confirmedCount}/{s.capacity??"sin límite"} lugares</small></button>)}</div>:null}
      {mode==="TURNO_RECURRENTE"?<AdminFormField label="Inscribir hasta (opcional)" icon={CalendarClock}><Input type="date" className={adminControlClass} value={form.fechaFin} onChange={e=>setForm(c=>({...c,fechaFin:e.target.value}))}/></AdminFormField>:null}
    </AdminFormCard>:null}
    <AdminFormCard title="Información adicional" description="Registrá observaciones internas relevantes para el seguimiento."><AdminFormField label="Observaciones administrativas" icon={FileText} align="start"><Textarea value={form.observaciones} onChange={e=>setForm(c=>({...c,observaciones:e.target.value}))} className={`${adminControlClass} min-h-32 resize-y py-3`} placeholder="Ingresá una observación opcional..."/></AdminFormField><p className="mt-3 flex gap-2 text-xs text-[var(--brand-muted)]"><Info className="size-4 shrink-0"/>Si falta documentación obligatoria, la inscripción quedará pendiente y no reservará cupo hasta regularizarla.</p></AdminFormCard>
    <Actions saving={saving} disabled={!validScope} backHref={backHref}/>
  </form>;
}

function Actions({saving,disabled=false,backHref="/enrollments"}:{saving:boolean;disabled?:boolean;backHref?:string}){const router=useRouter();return <div className="flex flex-col-reverse gap-3 border-t border-[var(--brand-border)] pt-6 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={()=>router.push(backHref)} className={adminSecondaryButtonClass}><ArrowLeft/>Volver</Button><Button type="submit" disabled={saving||disabled} className={adminPrimaryButtonClass}>{saving?<Loader2 className="animate-spin"/>:<Save/>}{saving?"Guardando...":"Inscribir ciudadano"}</Button></div>}
function buildScheduleSlots(schedule:ActivitySchedule){const duration=schedule.slotDurationMinutes;if(!duration)return[{horarioActividadId:schedule.id,horaInicio:schedule.startTime,horaFin:schedule.endTime,day:schedule.day,establishment:schedule.establishment.name}];const gap=schedule.slotGapMinutes||0,start=toMinutes(schedule.startTime),end=toMinutes(schedule.endTime),items:Array<{horarioActividadId:string;horaInicio:string;horaFin:string;day:string;establishment:string}>=[];for(let cursor=start;cursor+duration<=end;cursor+=duration+gap)items.push({horarioActividadId:schedule.id,horaInicio:toTime(cursor),horaFin:toTime(cursor+duration),day:schedule.day,establishment:schedule.establishment.name});return items;}
function formatScheduleSummary(items:ActivitySchedule[]){if(!items.length)return"Sin días ni horarios configurados";const groups=new Map<string,string[]>();items.slice().sort((a,b)=>dayOrder.indexOf(a.day)-dayOrder.indexOf(b.day)).forEach(item=>{const key=`${item.startTime} a ${item.endTime}`;groups.set(key,[...(groups.get(key)??[]),dayLabels[item.day]?.label??item.day] satisfies string[]);});return [...groups.entries()].map(([time,days])=>`${days.join(", ")} · ${time}`).join(" | ");}
function toMinutes(value:string){const[hour,minute]=value.split(":").map(Number);return hour*60+minute;}
function toTime(value:number){return `${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;}
