"use client";
import { useEffect,useMemo,useState } from "react";
import { CalendarDays,ChevronRight,Clock3,MapPin,Users } from "lucide-react";
import { useRouter,useSearchParams } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CATALOG_PAGE_SIZE,CatalogDetailField,CatalogEmptyState,CatalogFilterPopover,CatalogLoadingState,CatalogPageHeader,CatalogPagination,CatalogSearchInput } from "@/features/activity-catalogs/components/CatalogPrimitives";
import { cn } from "@/lib/utils";
import { useAttendanceSessions } from "../hooks/useAttendance";
import type { AttendanceFilters,AttendanceSession } from "../types/attendance.types";

const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Argentina/Buenos_Aires",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const filterSections=(state:string,setState:(value:string)=>void,status:string,setStatus:(value:string)=>void)=>[{id:"attendance",title:"Estado de asistencia",value:state,options:[{value:"all",label:"Todas"},{value:"PENDING",label:"Sin registrar"},{value:"OPEN",label:"Abiertas"},{value:"CLOSED",label:"Cerradas"}],onChange:setState},{id:"session",title:"Estado de clase",value:status,options:[{value:"all",label:"Todos"},{value:"PROGRAMADA",label:"Programadas"},{value:"EN_CURSO",label:"En curso"},{value:"FINALIZADA",label:"Finalizadas"},{value:"SUSPENDIDA",label:"Suspendidas"},{value:"CANCELADA",label:"Canceladas"}],onChange:setStatus}];

export function AttendancePage({workspace="administration"}:{workspace?:"administration"|"teacher"}){
  const router=useRouter(),params=useSearchParams(),[search,setSearch]=useState(params.get("search")??""),[state,setState]=useState(params.get("attendanceState")??"all"),[status,setStatus]=useState(params.get("status")??"all"),[dateFrom,setDateFrom]=useState(params.get("dateFrom")??today),[dateTo,setDateTo]=useState(params.get("dateTo")??today),[page,setPage]=useState(1),[selectedId,setSelectedId]=useState("");
  const filters=useMemo<AttendanceFilters>(()=>({search:search||undefined,attendanceState:state==="all"?undefined:state as AttendanceFilters["attendanceState"],status:status==="all"?undefined:status,dateFrom:dateFrom||undefined,dateTo:dateTo||undefined,userId:workspace==="administration"?params.get("userId")??undefined:undefined,page,pageSize:CATALOG_PAGE_SIZE}),[search,state,status,dateFrom,dateTo,page,params,workspace]);
  const{data,meta,loading,error}=useAttendanceSessions(filters,workspace);
  useEffect(()=>setSelectedId(current=>current&&data.some(item=>item.id===current)?current:data[0]?.id??""),[data]);
  if(loading)return <CatalogLoadingState label="asistencias" fullPage/>;
  const selected=data.find(item=>item.id===selectedId)??null,sections=filterSections(state,setState,status,setStatus);
  const open=(item:AttendanceSession)=>router.push(workspace==="teacher"?`/teacher/attendance/${item.id}`:`/attendance/${item.id}`);
  return <>
    {workspace==="teacher"?<div className="md:hidden"><TeacherMobileAttendanceList data={data} total={meta.total} error={error} search={search} setSearch={setSearch} state={state} status={status} sections={sections} dateFrom={dateFrom} setDateFrom={setDateFrom} dateTo={dateTo} setDateTo={setDateTo} page={page} setPage={setPage} onOpen={open}/></div>:null}
    <div className={workspace==="teacher"?"hidden md:block":"block"}><main className="min-h-[calc(100dvh-var(--topbar-h)-48px)] overflow-x-hidden bg-[var(--brand-page)] p-4 sm:p-6 lg:p-8"><CatalogPageHeader title="Asistencias" description={workspace==="teacher"?"Consultá tus clases y registrá la asistencia de los participantes.":"Consultá las clases del día y corregí planillas actuales o históricas."} total={meta.total}/><div className="mt-6 grid min-h-0 gap-6 xl:grid-cols-[minmax(340px,.9fr)_minmax(420px,1.1fr)]"><section className={cn("min-w-0",selectedId&&"hidden xl:block")}><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><CatalogSearchInput value={search} onChange={value=>{setSearch(value);setPage(1)}} placeholder="Buscar actividad o establecimiento..."/><CatalogFilterPopover sections={sections}/></div><DateRange dateFrom={dateFrom} setDateFrom={setDateFrom} dateTo={dateTo} setDateTo={setDateTo} setPage={setPage}/>{error?<p className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4">No pudimos cargar las asistencias.</p>:!data.length?<div className="mt-4"><CatalogEmptyState title="No tenés clases disponibles para registrar asistencia en este período." description="Probá modificar las fechas o los filtros seleccionados." filtered={Boolean(search||state!=="all"||status!=="all")}/></div>:<div className="mt-4 grid gap-3 overflow-y-auto pr-1 xl:max-h-[calc(100dvh-var(--topbar-h)-360px)]">{data.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} className={cn("rounded-2xl border p-4 text-left transition",selectedId===item.id?"border-[var(--brand-primary)] bg-[var(--brand-panel)] shadow-sm":"border-[var(--brand-border-soft)] bg-white hover:border-[var(--brand-secondary)]")}><div className="flex justify-between gap-3"><div><p className="font-extrabold text-[var(--brand-ink)]">{item.activity.name}</p><p className="mt-1 text-sm font-bold text-[var(--brand-primary)]">{formatDate(item.date)} · {item.startTime} a {item.endTime}</p><p className="text-xs text-[var(--brand-muted)]">{item.establishment.name}</p></div><StateBadge state={item.attendanceState}/></div><p className="mt-3 text-xs text-[var(--brand-muted)]">{item.summary.presentCount} presentes · {item.summary.absentCount} ausentes · {item.summary.unregisteredCount} sin registrar</p></button>)}</div>}<CatalogPagination page={page} total={meta.total} onPageChange={setPage}/></section><AttendanceDetail item={selected} onBack={()=>setSelectedId("")} onOpen={()=>selected&&open(selected)}/></div></main></div>
  </>;
}

type MobileListProps={data:AttendanceSession[];total:number;error:boolean;search:string;setSearch:(value:string)=>void;state:string;status:string;sections:ReturnType<typeof filterSections>;dateFrom:string;setDateFrom:(value:string)=>void;dateTo:string;setDateTo:(value:string)=>void;page:number;setPage:(value:number)=>void;onOpen:(item:AttendanceSession)=>void};
function TeacherMobileAttendanceList({data,total,error,search,setSearch,state,status,sections,dateFrom,setDateFrom,dateTo,setDateTo,page,setPage,onOpen}:MobileListProps){return <main className="min-h-full bg-[var(--brand-page)] px-4 py-5"><header className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-[var(--brand-primary)]">Tomar asistencia</h1><p className="mt-1 text-sm leading-5 text-[var(--brand-muted)]">Seleccioná una de tus clases asignadas.</p></div><span className="grid min-w-9 place-items-center rounded-full bg-[var(--brand-primary)] px-2 py-1 text-xs font-bold text-white">{total}</span></header><div className="mt-5 grid grid-cols-[minmax(0,1fr)_auto] gap-2"><CatalogSearchInput value={search} onChange={value=>{setSearch(value);setPage(1)}} placeholder="Buscar clases..."/><CatalogFilterPopover sections={sections}/></div><DateRange dateFrom={dateFrom} setDateFrom={setDateFrom} dateTo={dateTo} setDateTo={setDateTo} setPage={setPage}/>{error?<p className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm">No pudimos cargar las asistencias.</p>:!data.length?<div className="mt-4"><CatalogEmptyState title="No tenés clases disponibles para registrar asistencia en este período." description="Probá modificar las fechas o los filtros seleccionados." filtered={Boolean(search||state!=="all"||status!=="all")}/></div>:<div className="mt-4 grid gap-3">{data.map((item)=>{const future=item.date>today,blocked=["SUSPENDIDA","CANCELADA","FINALIZADA"].includes(item.status);return <article key={item.id} className="rounded-2xl border border-[var(--brand-border-soft)] bg-[#F9FAF5] p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="truncate font-extrabold text-[var(--brand-ink)]">{item.activity.name}</h2><p className="mt-1 flex items-center gap-1 text-xs font-bold text-[var(--brand-primary)]"><CalendarDays className="size-3.5"/>{formatDate(item.date)}</p></div><StateBadge state={item.attendanceState}/></div><div className="mt-3 space-y-1 text-xs text-[var(--brand-muted)]"><p className="flex items-center gap-1.5"><Clock3 className="size-3.5"/>{item.startTime} a {item.endTime}</p><p className="flex items-start gap-1.5"><MapPin className="mt-0.5 size-3.5 shrink-0"/>{item.establishment.name}{item.space?` · ${item.space}`:""}</p><p>{item.summary.eligibleCount} inscriptos · {item.summary.unregisteredCount} sin registrar</p></div><Button disabled={future||blocked} onClick={()=>onOpen(item)} className="mt-4 h-10 w-full rounded-xl bg-[var(--brand-primary)] text-xs font-bold">{blocked?"Asistencia no disponible":future?"Disponible el día de la clase":item.attendanceState==="CLOSED"?"Ver planilla":"Tomar asistencia"}{!future&&!blocked?<ChevronRight/>:null}</Button></article>})}</div>}<div className="mt-4"><CatalogPagination page={page} total={total} onPageChange={setPage}/></div></main>}

function DateRange({dateFrom,setDateFrom,dateTo,setDateTo,setPage}:{dateFrom:string;setDateFrom:(value:string)=>void;dateTo:string;setDateTo:(value:string)=>void;setPage:(value:number)=>void}){const mobileInputClass="max-md:min-w-0 max-md:px-2 max-md:text-xs max-md:[&::-webkit-calendar-picker-indicator]:m-0 max-md:[&::-webkit-calendar-picker-indicator]:ml-1 max-md:[&::-webkit-calendar-picker-indicator]:shrink-0";return <div className="mt-3 grid grid-cols-2 gap-2 rounded-2xl border border-[var(--brand-border-soft)] bg-white/60 p-3 max-md:min-w-0 max-[360px]:gap-1.5 max-[360px]:px-2"><Input className={mobileInputClass} aria-label="Fecha desde" type="date" max={dateTo||today} value={dateFrom} onChange={event=>{setDateFrom(event.target.value);setPage(1)}}/><Input className={mobileInputClass} aria-label="Fecha hasta" type="date" max={today} min={dateFrom||undefined} value={dateTo} onChange={event=>{setDateTo(event.target.value);setPage(1)}}/></div>}
function AttendanceDetail({item,onBack,onOpen}:{item:AttendanceSession|null;onBack:()=>void;onOpen:()=>void}){if(!item)return <aside className="hidden rounded-3xl border border-[var(--brand-border-soft)] bg-[var(--brand-panel)] p-8 xl:grid xl:place-items-center"><p className="text-sm font-bold text-[var(--brand-muted)]">Seleccioná una clase.</p></aside>;const future=item.date>today,blocked=["SUSPENDIDA","CANCELADA","FINALIZADA"].includes(item.status);return <aside className="min-h-0 overflow-y-auto rounded-3xl border border-[var(--brand-border-soft)] bg-[var(--brand-panel)] p-6 shadow-sm"><Button variant="ghost" className="mb-3 xl:hidden" onClick={onBack}>← Volver al listado</Button><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-extrabold text-[var(--brand-primary)]">{item.activity.name}</h2><div className="mt-2"><StateBadge state={item.attendanceState}/></div></div><Button disabled={future||blocked} onClick={onOpen} className="h-11 rounded-xl bg-[var(--brand-primary)] px-5 font-bold">{blocked?"Asistencia no disponible":future?"Disponible el día de la clase":item.attendanceState==="CLOSED"?"Ver planilla":"Tomar asistencia"}{!future&&!blocked?<ChevronRight/>:null}</Button></div><dl className="mt-6 grid gap-3"><CatalogDetailField icon={CalendarDays} label="Fecha">{formatDate(item.date)}</CatalogDetailField><CatalogDetailField icon={Clock3} label="Horario">{item.startTime} a {item.endTime}</CatalogDetailField><CatalogDetailField icon={MapPin} label="Establecimiento">{item.establishment.name}{item.space?` · ${item.space}`:""}</CatalogDetailField><CatalogDetailField icon={Users} label="Profesores">{item.professors.join(", ")||"Sin informar"}</CatalogDetailField><CatalogDetailField icon={Users} label="Resumen">{item.summary.eligibleCount} inscriptos · {item.summary.presentCount} presentes · {item.summary.absentCount} ausentes · {item.summary.justifiedCount} justificadas · {item.summary.unregisteredCount} sin registrar</CatalogDetailField></dl></aside>}
function StateBadge({state}:{state:AttendanceSession["attendanceState"]}){const responsive=" h-6 rounded-full px-2 py-0 text-[9px] md:h-auto md:rounded-md md:py-0.5 md:text-xs";return <Badge variant="outline" className={(state==="CLOSED"?"border-[var(--brand-neutral)] bg-[var(--brand-neutral)]/15 text-[#555]":state==="OPEN"?"border-[var(--brand-secondary)]/40 bg-[var(--brand-highlight)] text-[var(--brand-primary)]":"border-amber-300 bg-amber-50 text-amber-800")+responsive}>{state==="CLOSED"?"Cerrada":state==="OPEN"?"En progreso":"Sin registrar"}</Badge>}
function formatDate(value:string){return new Date(`${value}T00:00:00`).toLocaleDateString("es-AR",{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"})}
