"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronRight, Clock3, MapPin, Users } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { CATALOG_PAGE_SIZE, CatalogDetailField, CatalogFilterPopover, CatalogLoadingState, CatalogPageHeader, CatalogPagination, CatalogSearchInput } from "@/features/activity-catalogs/components/CatalogPrimitives";
import { cn } from "@/lib/utils";
import { useAttendanceSessions } from "../hooks/useAttendance";
import type { AttendanceFilters, AttendanceSession } from "../types/attendance.types";

const today = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());

export function AttendancePage() {
  const router = useRouter(), params = useSearchParams();
  const [search,setSearch]=useState(params.get("search")??""),[state,setState]=useState(params.get("attendanceState")??"all"),[status,setStatus]=useState(params.get("status")??"all"),[dateFrom,setDateFrom]=useState(params.get("dateFrom")??today),[dateTo,setDateTo]=useState(params.get("dateTo")??today),[page,setPage]=useState(1),[selectedId,setSelectedId]=useState("");
  const filters=useMemo<AttendanceFilters>(()=>({search:search||undefined,attendanceState:state==="all"?undefined:state as AttendanceFilters["attendanceState"],status:status==="all"?undefined:status,dateFrom:dateFrom||undefined,dateTo:dateTo||undefined,userId:params.get("userId")??undefined,page,pageSize:CATALOG_PAGE_SIZE}),[search,state,status,dateFrom,dateTo,page,params]);
  const {data,meta,loading,error}=useAttendanceSessions(filters);
  useEffect(()=>setSelectedId((current)=>current&&data.some((item)=>item.id===current)?current:data[0]?.id??""),[data]);
  if(loading)return <CatalogLoadingState label="asistencias" fullPage/>;
  const selected=data.find((item)=>item.id===selectedId)??null;
  return <main className="min-h-[calc(100dvh-var(--topbar-h)-48px)] bg-[#F7FBF5] p-4 sm:p-6 lg:p-8"><CatalogPageHeader title="Asistencias" description="Consultá las clases del día y corregí planillas actuales o históricas." total={meta.total}/><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(340px,.9fr)_minmax(420px,1.1fr)]"><section className={cn("min-w-0",selectedId&&"hidden xl:block")}><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><CatalogSearchInput value={search} onChange={(value)=>{setSearch(value);setPage(1)}} placeholder="Buscar actividad o establecimiento..."/><CatalogFilterPopover sections={[{id:"attendance",title:"Estado de asistencia",value:state,options:[{value:"all",label:"Todas"},{value:"PENDING",label:"Sin registrar"},{value:"OPEN",label:"Abiertas"},{value:"CLOSED",label:"Cerradas"}],onChange:setState},{id:"session",title:"Estado de clase",value:status,options:[{value:"all",label:"Todos"},{value:"PROGRAMADA",label:"Programadas"},{value:"EN_CURSO",label:"En curso"},{value:"FINALIZADA",label:"Finalizadas"},{value:"SUSPENDIDA",label:"Suspendidas"},{value:"CANCELADA",label:"Canceladas"}],onChange:setStatus}]}/></div><div className="mt-3 grid gap-3 rounded-2xl border border-[#DDE8D7] bg-white/60 p-3 sm:grid-cols-2"><Input aria-label="Fecha desde" type="date" max={dateTo||today} value={dateFrom} onChange={(event)=>{setDateFrom(event.target.value);setPage(1)}}/><Input aria-label="Fecha hasta" type="date" max={today} min={dateFrom||undefined} value={dateTo} onChange={(event)=>{setDateTo(event.target.value);setPage(1)}}/></div>{error?<p className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4">No pudimos cargar las asistencias.</p>:<div className="mt-4 grid gap-3">{data.map((item)=><button key={item.id} data-admin-list-card="" onClick={()=>setSelectedId(item.id)} className={cn("self-start rounded-2xl border p-3 text-left transition",selectedId===item.id?"border-[#1D4F36] bg-[#EEF6E9] shadow-sm":"border-[#DDE8D7] bg-white hover:border-[#819B56]")}><div className="flex justify-between gap-3"><div><p className="font-extrabold text-[#173C2A]">{item.activity.name}</p><p className="mt-1 text-sm font-bold text-[#1D4F36]">{formatDate(item.date)} · {item.startTime} a {item.endTime}</p><p className="text-xs text-[#5F6F68]">{item.establishment.name}</p></div><StateBadge state={item.attendanceState}/></div><p className="mt-3 text-xs text-[#5F6F68]">{item.summary.presentCount} presentes · {item.summary.absentCount} ausentes · {item.summary.unregisteredCount} sin registrar</p></button>)}</div>}<CatalogPagination page={page} total={meta.total} onPageChange={setPage}/></section><AttendanceDetail item={selected} onBack={()=>setSelectedId("")} onOpen={()=>selected&&router.push(`/attendance/${selected.id}`)}/></div></main>;
}

function AttendanceDetail({item,onBack,onOpen}:{item:AttendanceSession|null;onBack:()=>void;onOpen:()=>void}){if(!item)return <aside className="hidden rounded-3xl border border-[#DDE8D7] bg-[#EEF6E9] p-8 xl:grid xl:place-items-center"><p className="text-sm font-bold text-[#5F6F68]">Seleccioná una clase.</p></aside>;const future=item.date>today;return <aside className="rounded-3xl border border-[#DDE8D7] bg-[#EEF6E9] p-6 shadow-sm"><Button variant="ghost" className="mb-3 xl:hidden" onClick={onBack}>← Volver al listado</Button><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-extrabold text-[#1D4F36]">{item.activity.name}</h2><div className="mt-2"><StateBadge state={item.attendanceState}/></div></div><Button disabled={future} onClick={onOpen} className="h-11 rounded-xl bg-[#1D4F36] px-5 font-bold">{future?"Disponible el día de la clase":item.attendanceState==="CLOSED"?"Ver planilla":"Tomar asistencia"}{!future?<ChevronRight/>:null}</Button></div><dl className="mt-6 grid gap-3"><CatalogDetailField icon={CalendarDays} label="Fecha">{formatDate(item.date)}</CatalogDetailField><CatalogDetailField icon={Clock3} label="Horario">{item.startTime} a {item.endTime}</CatalogDetailField><CatalogDetailField icon={MapPin} label="Establecimiento">{item.establishment.name}{item.space?` · ${item.space}`:""}</CatalogDetailField><CatalogDetailField icon={Users} label="Resumen">{item.summary.eligibleCount} inscriptos · {item.summary.presentCount} presentes · {item.summary.absentCount} ausentes · {item.summary.justifiedCount} justificadas</CatalogDetailField></dl></aside>}
function StateBadge({state}:{state:AttendanceSession["attendanceState"]}){return <Badge variant="outline" className={state==="CLOSED"?"border-[#B2B2B2] bg-[#B2B2B2]/15 text-[#555]":state==="OPEN"?"border-[#819B56]/40 bg-[#DDEED2] text-[#1D4F36]":"border-amber-300 bg-amber-50 text-amber-800"}>{state==="CLOSED"?"Cerrada":state==="OPEN"?"Abierta":"Sin registrar"}</Badge>}
function formatDate(value:string){return new Date(`${value}T00:00:00`).toLocaleDateString("es-AR",{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"})}
