import { CheckCircle2, CircleX, Clock3, UserRound } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import type { AccessValidationResponse } from "../types/access.types";
const labels: Record<string, string> = { USUARIO_HABILITADO: "Usuario habilitado", QR_INVALIDO: "QR inválido", QR_REVOCADO: "QR revocado", USUARIO_INACTIVO: "Usuario inactivo", USUARIO_ELIMINADO: "Usuario eliminado", SIN_INSCRIPCION: "Sin inscripción", INSCRIPCION_NO_CONFIRMADA: "Inscripción no confirmada", SIN_CLASE_HABILITADA: "Sin clase habilitada", FUERA_DE_HORARIO: "Fuera de horario", CLASE_SUSPENDIDA: "Clase suspendida", CLASE_CANCELADA: "Clase cancelada", ESTABLECIMIENTO_INCORRECTO: "Establecimiento incorrecto", ACCESO_MANUAL_AUTORIZADO: "Autorización manual", ACCESO_MANUAL_RECHAZADO: "Rechazo manual" };
export function AccessResultCard({ result, compactMobile = false }: { result: AccessValidationResponse; compactMobile?: boolean }) {
  const allowed = result.result === "PERMITIDO";
  return <section className={`rounded-3xl border border-[var(--brand-secondary)]/25 bg-white shadow-sm ${compactMobile ? "p-4" : "p-6"}`}>
    <div className={`flex items-start ${compactMobile ? "gap-3" : "gap-4"}`}><div className={`grid shrink-0 place-items-center ${compactMobile ? "size-11 rounded-xl" : "size-12 rounded-2xl"} ${allowed ? "bg-[var(--brand-accent)] text-[var(--brand-primary)]" : "bg-amber-100 text-amber-800"}`}>{allowed ? <CheckCircle2 /> : <CircleX />}</div><div><p className="text-xs font-bold uppercase tracking-wide text-[var(--brand-secondary)]">Resultado</p><h2 className="text-xl font-bold text-[var(--brand-primary)]">{allowed ? "Acceso permitido" : "Acceso rechazado"}</h2><p className="mt-1 text-sm text-[var(--brand-text)]">{result.message}</p></div></div>
    {result.user ? <div className={`flex items-center rounded-2xl bg-[var(--brand-page)] ${compactMobile ? "mt-4 gap-3 p-3" : "mt-6 gap-4 p-4"}`}><Avatar className={compactMobile ? "size-14 shrink-0 rounded-xl" : "size-24 rounded-2xl"}><AvatarImage src={result.user.profilePhotoUrl ?? undefined} alt="Foto de identidad"/><AvatarFallback><UserRound /></AvatarFallback></Avatar><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wide text-[var(--brand-secondary)]">Verificación visual</p><p className="break-words font-bold text-[var(--brand-primary)]">{[result.user.nombre, result.user.apellido].filter(Boolean).join(" ")}</p><p className="text-sm text-[var(--brand-text)]">DNI {result.user.dni || "No informado"}</p><p className="mt-1 text-xs leading-4 text-[var(--brand-muted)]">Compará esta foto con la persona presente antes de autorizar el ingreso.</p></div></div> : null}
    <div className="mt-4 grid gap-2 text-sm text-[var(--brand-text)] sm:grid-cols-2"><p><strong>Motivo:</strong> {labels[result.reason] ?? result.reason}</p><p className="flex items-center gap-1"><Clock3 className="size-4" /> {new Date(result.occurredAt).toLocaleString("es-AR")}</p>{result.matchedSession ? <p className="sm:col-span-2"><strong>Clase:</strong> {result.matchedSession.activityName} · {result.matchedSession.startTime} a {result.matchedSession.endTime}</p> : null}</div>
  </section>;
}
