"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { registerManualAccess, searchAccessPeople } from "../services/access.service";
import type { AccessPerson, AccessValidationResponse } from "../types/access.types";
import { AccessPersonAvatar } from "./AccessPersonAvatar";
import { AccessResultCard } from "./AccessResultCard";
import { AccessShell } from "./AccessShell";
type SearchPerson = AccessPerson & { validation: AccessValidationResponse };
export function AccessManualPage() { return <AccessShell title="Búsqueda manual" description="Buscá por DNI, nombre, apellido, email o identificador.">{({ establishmentId }) => <Manual establishmentId={establishmentId}/>}</AccessShell>; }
function Manual({ establishmentId }: { establishmentId: string }) {
  const [query, setQuery] = useState(""); const [items, setItems] = useState<SearchPerson[]>([]); const [selected, setSelected] = useState<SearchPerson | null>(null); const [observation, setObservation] = useState(""); const [result, setResult] = useState<AccessValidationResponse | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { const q = query.trim(); if (!establishmentId || q.length < 2) { setItems([]); return; } const timeout = window.setTimeout(() => { setLoading(true); void searchAccessPeople(establishmentId, q).then((response) => { setItems(response.data); setSelected(response.data[0] ?? null); }).finally(() => setLoading(false)); }, 350); return () => window.clearTimeout(timeout); }, [establishmentId, query]);
  async function register(decision: "ALLOW" | "REJECT") { if (!selected || observation.trim().length < 5) return; setLoading(true); try { setResult(await registerManualAccess({ establishmentId, userId: selected.id, decision, observation })); } finally { setLoading(false); } }
  if (!establishmentId) return <div className="grid min-h-64 place-items-center rounded-3xl border border-dashed border-[var(--brand-secondary)]/40 bg-white text-[var(--brand-text)]">Seleccioná un establecimiento para buscar.</div>;
  if (result) return <div className="grid gap-4"><AccessResultCard result={result}/><Button className="w-fit" variant="outline" onClick={() => { setResult(null); setObservation(""); }}>Nueva búsqueda</Button></div>;
  return <div className="grid gap-5"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por DNI, nombre, apellido, email o ID..." className="h-12 rounded-2xl border-[var(--brand-secondary)]/35 bg-white"/><div className="grid min-h-96 gap-6 lg:grid-cols-[1fr_1fr]"><section className="rounded-3xl border border-[var(--brand-secondary)]/25 bg-white p-4">{loading && !items.length ? <div className="h-60 animate-pulse rounded-2xl bg-[var(--brand-panel)]"/> : items.length ? <div className="grid gap-2">{items.map((item) => <button key={item.id} type="button" data-admin-list-card="" onClick={() => setSelected(item)} className={`flex self-start items-center gap-3 rounded-2xl border p-3 text-left ${selected?.id === item.id ? "border-[var(--brand-primary)] bg-[var(--brand-panel)]" : "border-transparent bg-[var(--brand-page)]"}`}><AccessPersonAvatar person={item}/><span><strong className="block text-[var(--brand-primary)]">{[item.nombre, item.apellido].filter(Boolean).join(" ")}</strong><small className="text-[var(--brand-text)]">DNI {item.dni || "No informado"} · {item.estado}</small></span></button>)}</div> : <div className="grid min-h-60 place-items-center text-sm text-[var(--brand-text)]">Ingresá al menos dos caracteres.</div>}</section><section className="rounded-3xl border border-[var(--brand-secondary)]/25 bg-white p-6">{selected ? <div className="grid gap-4"><div><h2 className="text-lg font-bold text-[var(--brand-primary)]">{[selected.nombre, selected.apellido].filter(Boolean).join(" ")}</h2><p className="text-sm text-[var(--brand-text)]">Validación actual: {selected.validation.message}</p>{selected.validation.matchedSession ? <p className="mt-1 text-sm text-[var(--brand-text)]">Próxima clase: {selected.validation.matchedSession.activityName}</p> : null}</div><Textarea value={observation} onChange={(event) => setObservation(event.target.value)} placeholder="Observación obligatoria para el registro manual"/><p className="text-xs text-[var(--brand-text)]">Mínimo 5 caracteres. La acción quedará auditada.</p><div className="flex gap-3"><Button disabled={loading || observation.trim().length < 5} onClick={() => void register("ALLOW")}>Permitir ingreso</Button><Button variant="outline" disabled={loading || observation.trim().length < 5} onClick={() => void register("REJECT")}>Rechazar ingreso</Button></div></div> : <div className="grid min-h-60 place-items-center text-sm text-[var(--brand-text)]">Seleccioná una persona.</div>}</section></div></div>;
}
