import { CheckCircle2, CircleX, Clock3, UserRound } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import type { AccessValidationResponse } from "../types/access.types";
const labels: Record<string, string> = { USUARIO_HABILITADO: "Usuario habilitado", QR_INVALIDO: "QR inválido", QR_REVOCADO: "QR revocado", USUARIO_INACTIVO: "Usuario inactivo", USUARIO_ELIMINADO: "Usuario eliminado", SIN_INSCRIPCION: "Sin inscripción", INSCRIPCION_NO_CONFIRMADA: "Inscripción no confirmada", SIN_CLASE_HABILITADA: "Sin clase habilitada", FUERA_DE_HORARIO: "Fuera de horario", CLASE_SUSPENDIDA: "Clase suspendida", CLASE_CANCELADA: "Clase cancelada", ESTABLECIMIENTO_INCORRECTO: "Establecimiento incorrecto", ACCESO_MANUAL_AUTORIZADO: "Autorización manual", ACCESO_MANUAL_RECHAZADO: "Rechazo manual" };
export function AccessResultCard({ result }: { result: AccessValidationResponse }) {
  const allowed = result.result === "PERMITIDO";
  return <section className="rounded-3xl border border-[#819B56]/25 bg-white p-6 shadow-sm">
    <div className="flex items-start gap-4"><div className={`grid size-12 place-items-center rounded-2xl ${allowed ? "bg-[#DDEF8F] text-[#1D4F36]" : "bg-amber-100 text-amber-800"}`}>{allowed ? <CheckCircle2 /> : <CircleX />}</div><div><p className="text-xs font-bold uppercase tracking-wide text-[#819B56]">Resultado</p><h2 className="text-xl font-bold text-[#1D4F36]">{allowed ? "Acceso permitido" : "Acceso rechazado"}</h2><p className="mt-1 text-sm text-[#315644]">{result.message}</p></div></div>
    {result.user ? <div className="mt-6 flex items-center gap-4 rounded-2xl bg-[#F7FBF5] p-4"><Avatar className="size-24 rounded-2xl"><AvatarImage src={result.user.profilePhotoUrl ?? undefined} alt="Foto de identidad"/><AvatarFallback><UserRound /></AvatarFallback></Avatar><div><p className="text-xs font-bold uppercase tracking-wide text-[#819B56]">Verificación visual</p><p className="font-bold text-[#1D4F36]">{[result.user.nombre, result.user.apellido].filter(Boolean).join(" ")}</p><p className="text-sm text-[#315644]">DNI {result.user.dni || "No informado"}</p><p className="mt-1 text-xs text-[#5F6F68]">Compará esta foto con la persona presente antes de autorizar el ingreso.</p></div></div> : null}
    <div className="mt-4 grid gap-2 text-sm text-[#315644] sm:grid-cols-2"><p><strong>Motivo:</strong> {labels[result.reason] ?? result.reason}</p><p className="flex items-center gap-1"><Clock3 className="size-4" /> {new Date(result.occurredAt).toLocaleString("es-AR")}</p>{result.matchedSession ? <p className="sm:col-span-2"><strong>Clase:</strong> {result.matchedSession.activityName} · {result.matchedSession.startTime} a {result.matchedSession.endTime}</p> : null}</div>
  </section>;
}
