import { ClaseActividadEstado, DiaSemana, Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import { CatalogConflictError, CatalogNotFoundError, CatalogValidationError } from "@/lib/errors/catalog-errors";
import { createActivitySessionSchema, generateActivitySessionsSchema } from "../schemas/activity-session.schema";
import type { ActivitySessionFilters,CreateActivitySessionInput,GenerateActivitySessionsInput,UpdateActivitySessionInput } from "../types/activity-session.types";
import { createNotifications } from "@/features/notifications/services/notifications.server";

const include={horarioActividad:{include:{actividad:{select:{id:true,nombre:true,modalidadInscripcion:true}}}},establecimiento:{select:{id:true,nombre:true,direccion:true}},profesores:{include:{profesor:{include:{usuario:{select:{nombre:true,apellido:true}}}}}}} satisfies Prisma.ClaseActividadInclude;
const dayIndex:Record<DiaSemana,number>={DOMINGO:0,LUNES:1,MARTES:2,MIERCOLES:3,JUEVES:4,VIERNES:5,SABADO:6};
const dateValue=(v:string)=>new Date(`${v}T00:00:00.000Z`);const dateText=(v:Date)=>v.toISOString().slice(0,10);const clean=(v?:string|null)=>v?.trim()||null;const normalized=(v?:string|null)=>clean(v)?.replace(/\s+/g," ").toLocaleLowerCase("es")??null;
const timeMinutes=(value:string)=>{const[hours,minutes]=value.split(":").map(Number);return hours*60+minutes};const timeText=(minutes:number)=>`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;
type Counts=Map<string,{confirmedCount:number;waitlistCount:number}>;
async function counts(tx:Prisma.TransactionClient,sessions:any[]):Promise<Counts>{const result:Counts=new Map();await Promise.all(sessions.map(async(row)=>{if(row.horarioActividad.actividad.modalidadInscripcion==="POR_CLASE"){const grouped=await tx.reservaClase.groupBy({by:["estado"],where:{claseActividadId:row.id,estado:{in:["RESERVADA","LISTA_ESPERA","OFRECIDA"]}},_count:{_all:true}});result.set(row.id,{confirmedCount:grouped.find(x=>x.estado==="RESERVADA")?._count._all??0,waitlistCount:grouped.filter(x=>x.estado!=="RESERVADA").reduce((sum,x)=>sum+x._count._all,0)});return;}const[confirmedCount,waitlistCount]=await Promise.all([tx.inscripcion.count({where:{horarioActividadId:row.horarioActividadId,estado:"CONFIRMADA",OR:[{fechaInicio:null},{fechaInicio:{lte:row.fecha}}],AND:[{OR:[{fechaFin:null},{fechaFin:{gte:row.fecha}}]}],reservas:{none:{claseActividadId:row.id,estado:"AUSENCIA_INFORMADA"}}}}),tx.inscripcion.count({where:{horarioActividadId:row.horarioActividadId,estado:"LISTA_ESPERA"}})]);result.set(row.id,{confirmedCount,waitlistCount});}));return result;}
function map(row:any,summary:Counts){const c=summary.get(row.id)??{confirmedCount:0,waitlistCount:0};return{id:row.id,date:dateText(row.fecha),startTime:row.horaInicio,endTime:row.horaFin,status:row.estado,space:row.espacio,capacity:row.cupoMaximo,cancellationReason:row.motivoCancelacion,observations:row.observaciones,activitySchedule:{id:row.horarioActividad.id,day:row.horarioActividad.diaSemana,activity:{id:row.horarioActividad.actividad.id,name:row.horarioActividad.actividad.nombre}},establishment:{id:row.establecimiento.id,name:row.establecimiento.nombre,address:row.establecimiento.direccion},professors:row.profesores.map((x:any)=>({id:x.profesor.id,fullName:[x.profesor.usuario.nombre,x.profesor.usuario.apellido].filter(Boolean).join(" "),specialty:x.profesor.especialidad,status:x.profesor.estado,isPrimary:x.esPrincipal})),enrollmentSummary:c,createdAt:row.createdAt,updatedAt:row.updatedAt};}
async function schedule(tx:Prisma.TransactionClient,id:string){const item=await tx.horarioActividad.findUnique({where:{id},include:{profesores:true,actividad:true,recursos:{include:{recurso:true}}}});if(!item)throw new CatalogNotFoundError("Horario no encontrado.");if(["CANCELADO","FINALIZADO"].includes(item.estado))throw new CatalogValidationError("El horario no admite nuevas clases.");return item;}
function validateDay(date:string,day:DiaSemana){if(dateValue(date).getUTCDay()!==dayIndex[day])throw new CatalogValidationError("La fecha no coincide con el día semanal del horario.");}
async function validateProfessors(tx:Prisma.TransactionClient,ids:string[],oldIds=new Set<string>()){if(new Set(ids).size!==ids.length)throw new CatalogValidationError("No repitas profesores.");const rows=await tx.profesor.findMany({where:{id:{in:ids}},include:{usuario:{select:{nombre:true,apellido:true}}}});if(rows.length!==ids.length)throw new CatalogValidationError("Uno o más profesores no existen.");const invalid=rows.find(x=>x.estado!=="ACTIVO"&&!oldIds.has(x.id));if(invalid)throw new CatalogValidationError("No se pueden agregar profesores inactivos o suspendidos.");}
async function conflicts(tx:Prisma.TransactionClient,input:any,excludeId?:string){if(["CANCELADA","SUSPENDIDA"].includes(input.status))return;const rows=await tx.claseActividad.findMany({where:{id:excludeId?{not:excludeId}:undefined,fecha:dateValue(input.date),estado:{notIn:["CANCELADA","SUSPENDIDA"]},horaInicio:{lt:input.endTime},horaFin:{gt:input.startTime},OR:[{establecimientoId:input.establishmentId},{profesores:{some:{profesorId:{in:input.professorIds}}}}]},include:{horarioActividad:{include:{actividad:true}},establecimiento:true,profesores:{include:{profesor:{include:{usuario:true}}}}}});for(const row of rows){const teacher=row.profesores.find(x=>input.professorIds.includes(x.profesorId));if(teacher)throw new CatalogConflictError(`${teacher.profesor.usuario.nombre} ${teacher.profesor.usuario.apellido} ya tiene ${row.horarioActividad.actividad.nombre} de ${row.horaInicio} a ${row.horaFin}.`);if(input.space&&row.establecimientoId===input.establishmentId&&normalized(row.espacio)===normalized(input.space))throw new CatalogConflictError(`El espacio ${input.space} ya está ocupado de ${row.horaInicio} a ${row.horaFin}.`);}}
async function createInTx(tx:Prisma.TransactionClient,raw:CreateActivitySessionInput){const parsed=createActivitySessionSchema.parse(raw),source=await schedule(tx,parsed.activityScheduleId);validateDay(parsed.date,source.diaSemana);const professorIds=parsed.professorIds??source.profesores.map(x=>x.profesorId),primaryProfessorId=parsed.primaryProfessorId===undefined?(source.profesores.find(x=>x.esPrincipal)?.profesorId??null):parsed.primaryProfessorId;const input={...parsed,startTime:parsed.startTime??source.horaInicio,endTime:parsed.endTime??source.horaFin,establishmentId:parsed.establishmentId??source.establecimientoId,space:parsed.space===undefined?source.espacio:clean(parsed.space),capacity:parsed.capacity??source.cupoMaximo,observations:clean(parsed.observations),status:parsed.status??"PROGRAMADA",professorIds,primaryProfessorId};if(input.startTime>=input.endTime)throw new CatalogValidationError("La hora final debe ser posterior a la inicial.");if(primaryProfessorId&&!professorIds.includes(primaryProfessorId))throw new CatalogValidationError("El profesor principal debe estar seleccionado.");await validateProfessors(tx,professorIds);await conflicts(tx,input);const row=await tx.claseActividad.create({data:{horarioActividadId:input.activityScheduleId,fecha:dateValue(input.date),horaInicio:input.startTime,horaFin:input.endTime,establecimientoId:input.establishmentId,espacio:input.space,cupoMaximo:input.capacity,estado:input.status,motivoCancelacion:input.status==="CANCELADA"?input.cancellationReason:null,observaciones:input.observations,profesores:{create:professorIds.map(id=>({profesorId:id,esPrincipal:id===primaryProfessorId}))}},include});if(!["TURNO_RECURRENTE","TURNO_PUNTUAL","ACCESO_LIBRE"].includes(source.actividad.modalidadOperacion)&&input.status==="PROGRAMADA"&&source.recursos.length)await tx.bloqueoRecurso.createMany({data:source.recursos.map(item=>({recursoId:item.recursoId,claseActividadId:row.id,fecha:dateValue(input.date),horaInicio:input.startTime,horaFin:input.endTime,cantidad:item.cantidadReservada,motivo:`${source.actividad.nombre} · clase programada`,origen:"CLASE"}))});return row;}
export async function createActivitySession(input:CreateActivitySessionInput){return prisma.$transaction(async tx=>{const row=await createInTx(tx,input),summary=await counts(tx,[row]);return map(row,summary);});}
export async function generateActivitySessions(raw:GenerateActivitySessionsInput){
  const input=generateActivitySessionsSchema.parse(raw);
  return prisma.$transaction(async tx=>{
    const source=await schedule(tx,input.activityScheduleId),excluded=new Set(input.excludedDates),dates:string[]=[];
    for(let cursor=dateValue(input.dateFrom);cursor<=dateValue(input.dateTo);cursor=new Date(cursor.getTime()+86400000)){
      const text=dateText(cursor);
      if(cursor.getUTCDay()===dayIndex[source.diaSemana]&&!excluded.has(text))dates.push(text);
    }
    const slotMode=["TURNO_RECURRENTE","TURNO_PUNTUAL"].includes(source.actividad.modalidadOperacion),duration=source.duracionTurnoMinutos??source.actividad.duracionTurnoMinutos,gap=source.intervaloTurnoMinutos??source.actividad.intervaloTurnoMinutos,slots:Array<{startTime:string;endTime:string}>=[];
    if(slotMode){
      if(!duration)throw new CatalogValidationError("La actividad requiere una duración de turno.");
      for(let start=timeMinutes(source.horaInicio);start+duration<=timeMinutes(source.horaFin);start+=duration+gap)slots.push({startTime:timeText(start),endTime:timeText(start+duration)});
    }else slots.push({startTime:source.horaInicio,endTime:source.horaFin});
    if(dates.length*slots.length>180)throw new CatalogValidationError("No se pueden generar más de 180 turnos por operación.");
    const existing=await tx.claseActividad.findMany({
      where:{horarioActividadId:input.activityScheduleId,fecha:{in:dates.map(dateValue)}},
      select:{id:true,fecha:true,horaInicio:true,horaFin:true,estado:true,_count:{select:{asistencias:true,reservas:true,registrosAcceso:true}}},
    });
    const expectedEndByStart=new Map(slots.map(slot=>[slot.startTime,slot.endTime]));
    const today=dateValue(dateText(new Date()));
    for(const row of existing){
      const expectedEnd=expectedEndByStart.get(row.horaInicio);
      const canNormalize=slotMode&&expectedEnd&&expectedEnd!==row.horaFin&&row.estado==="PROGRAMADA"&&row.fecha>=today&&row._count.asistencias===0&&row._count.reservas===0&&row._count.registrosAcceso===0;
      if(canNormalize){
        await tx.claseActividad.update({where:{id:row.id},data:{horaFin:expectedEnd}});
        row.horaFin=expectedEnd;
      }
    }
    const existingSet=new Set(existing.map(x=>`${dateText(x.fecha)}:${x.horaInicio}`)),created:string[]=[],skipped:string[]=[];
    for(const date of dates)for(const slot of slots){
      const key=`${date}:${slot.startTime}`;
      if(existingSet.has(key)){skipped.push(key);continue;}
      await createInTx(tx,{activityScheduleId:input.activityScheduleId,date,startTime:slot.startTime,endTime:slot.endTime});
      created.push(key);
    }
    return{createdDates:created,skippedDates:skipped,excludedDates:input.excludedDates};
  },{timeout:120_000});
}
export async function generateActivitySessionsBulk(raw:GenerateActivitySessionsInput){
  const input=generateActivitySessionsSchema.parse(raw);
  return prisma.$transaction(async tx=>{
    const source=await schedule(tx,input.activityScheduleId),excluded=new Set(input.excludedDates),dates:string[]=[];
    for(let cursor=dateValue(input.dateFrom);cursor<=dateValue(input.dateTo);cursor=new Date(cursor.getTime()+86400000)){const text=dateText(cursor);if(cursor.getUTCDay()===dayIndex[source.diaSemana]&&!excluded.has(text))dates.push(text);}
    const slotMode=["TURNO_RECURRENTE","TURNO_PUNTUAL"].includes(source.actividad.modalidadOperacion),duration=source.duracionTurnoMinutos??source.actividad.duracionTurnoMinutos,gap=source.intervaloTurnoMinutos??source.actividad.intervaloTurnoMinutos,slots:Array<{startTime:string;endTime:string}>=[];
    if(slotMode){if(!duration)throw new CatalogValidationError("La actividad requiere una duración de turno.");for(let start=timeMinutes(source.horaInicio);start+duration<=timeMinutes(source.horaFin);start+=duration+gap)slots.push({startTime:timeText(start),endTime:timeText(start+duration)});}else slots.push({startTime:source.horaInicio,endTime:source.horaFin});
    if(dates.length*slots.length>180)throw new CatalogValidationError("No se pueden generar más de 180 turnos por operación.");
    const existing=await tx.claseActividad.findMany({where:{horarioActividadId:source.id,fecha:{in:dates.map(dateValue)}},select:{fecha:true,horaInicio:true}}),existingSet=new Set(existing.map(item=>`${dateText(item.fecha)}:${item.horaInicio}`));
    const rows=dates.flatMap(date=>slots.filter(slot=>!existingSet.has(`${date}:${slot.startTime}`)).map(slot=>({horarioActividadId:source.id,fecha:dateValue(date),horaInicio:slot.startTime,horaFin:slot.endTime,establecimientoId:source.establecimientoId,espacio:source.espacio,cupoMaximo:source.cupoMaximo,estado:"PROGRAMADA" as const})));
    if(rows.length)await tx.claseActividad.createMany({data:rows,skipDuplicates:true});
    const created=await tx.claseActividad.findMany({where:{horarioActividadId:source.id,fecha:{in:dates.map(dateValue)}},select:{id:true,fecha:true,horaInicio:true,horaFin:true}});
    const professorIds=source.profesores.map(item=>item.profesorId),primaryId=source.profesores.find(item=>item.esPrincipal)?.profesorId??null;
    if(professorIds.length&&created.length)await tx.claseActividadProfesor.createMany({data:created.flatMap(item=>professorIds.map(profesorId=>({claseActividadId:item.id,profesorId,esPrincipal:profesorId===primaryId}))),skipDuplicates:true});
    if(!slotMode&&source.actividad.modalidadOperacion!=="ACCESO_LIBRE"&&source.recursos.length&&created.length)await tx.bloqueoRecurso.createMany({data:created.flatMap(item=>source.recursos.map(resource=>({recursoId:resource.recursoId,claseActividadId:item.id,fecha:item.fecha,horaInicio:item.horaInicio,horaFin:item.horaFin,cantidad:resource.cantidadReservada,motivo:`${source.actividad.nombre} · clase programada`,origen:"CLASE" as const})))});
    return{createdDates:rows.map(item=>`${dateText(item.fecha)}:${item.horaInicio}`),skippedDates:[...existingSet],excludedDates:input.excludedDates};
  },{timeout:30_000});
}

export async function getActivitySession(id:string){return prisma.$transaction(async tx=>{const row=await tx.claseActividad.findUnique({where:{id},include});if(!row)return null;return map(row,await counts(tx,[row]));});}
export async function updateActivitySession(id:string,patch:UpdateActivitySessionInput){return prisma.$transaction(async tx=>{
  const current=await tx.claseActividad.findUnique({where:{id},include:{profesores:true}});if(!current)throw new CatalogNotFoundError("Clase no encontrada.");
  const professorIds=patch.professorIds??current.profesores.map(x=>x.profesorId),primaryProfessorId=patch.primaryProfessorId===undefined?(current.profesores.find(x=>x.esPrincipal)?.profesorId??null):patch.primaryProfessorId,input={date:dateText(current.fecha),startTime:patch.startTime??current.horaInicio,endTime:patch.endTime??current.horaFin,establishmentId:patch.establishmentId??current.establecimientoId,space:patch.space===undefined?current.espacio:clean(patch.space),status:patch.status??current.estado,professorIds,primaryProfessorId};
  if(input.startTime>=input.endTime)throw new CatalogValidationError("La hora final debe ser posterior.");if(primaryProfessorId&&!professorIds.includes(primaryProfessorId))throw new CatalogValidationError("El principal debe estar seleccionado.");if(["CANCELADA","SUSPENDIDA"].includes(input.status)&&!clean(patch.cancellationReason)&&!current.motivoCancelacion)throw new CatalogValidationError(input.status==="SUSPENDIDA"?"Indicá el motivo de suspensión de la clase.":"Indicá el motivo de cancelación de la clase.");
  await validateProfessors(tx,professorIds,new Set(current.profesores.map(x=>x.profesorId)));await conflicts(tx,input,id);const syncProfessors=patch.professorIds!==undefined||patch.primaryProfessorId!==undefined;if(syncProfessors)await tx.claseActividadProfesor.deleteMany({where:{claseActividadId:id}});
  const row=await tx.claseActividad.update({where:{id},data:{horaInicio:input.startTime,horaFin:input.endTime,establecimientoId:input.establishmentId,espacio:input.space,cupoMaximo:patch.capacity===undefined?undefined:patch.capacity,estado:input.status,motivoCancelacion:["CANCELADA","SUSPENDIDA"].includes(input.status)?(clean(patch.cancellationReason)??current.motivoCancelacion):null,observaciones:patch.observations===undefined?undefined:clean(patch.observations),...(syncProfessors?{profesores:{create:professorIds.map(pid=>({profesorId:pid,esPrincipal:pid===primaryProfessorId}))}}:{})},include});
  if(["CANCELADA","SUSPENDIDA"].includes(input.status))await tx.bloqueoRecurso.deleteMany({where:{claseActividadId:id}});
  const meaningful=current.horaInicio!==input.startTime||current.horaFin!==input.endTime||current.establecimientoId!==input.establishmentId||current.espacio!==input.space;const reactivated=input.status==="PROGRAMADA"&&current.estado==="SUSPENDIDA";const event=input.status==="CANCELADA"&&current.estado!=="CANCELADA"?{type:"CLASE_CANCELADA" as const,title:"Clase cancelada",priority:"ALTA" as const}:input.status==="SUSPENDIDA"&&current.estado!=="SUSPENDIDA"?{type:"CLASE_SUSPENDIDA" as const,title:"Clase suspendida",priority:"NORMAL" as const}:reactivated?{type:"CLASE_MODIFICADA" as const,title:"Clase reactivada",priority:"NORMAL" as const}:meaningful?{type:"CLASE_MODIFICADA" as const,title:"Clase modificada",priority:"NORMAL" as const}:null;
  if(event){const scheduleInfo=await tx.horarioActividad.findUniqueOrThrow({where:{id:row.horarioActividadId},include:{actividad:true,inscripciones:{where:{estado:"CONFIRMADA",OR:[{modalidad:{not:"POR_CLASE"}},{reservas:{some:{claseActividadId:id,estado:"RESERVADA"}}}]},select:{usuarioId:true}},clases:{where:{id},select:{reservas:{where:{estado:{in:["LISTA_ESPERA","OFRECIDA"]}},select:{usuarioId:true}}}}}});const userIds=[...new Set([...scheduleInfo.inscripciones.map(x=>x.usuarioId),...(scheduleInfo.clases[0]?.reservas.map(x=>x.usuarioId)??[])])];const eventMessage=reactivated?"fue reactivada.":event.type==="CLASE_MODIFICADA"?"cambió.":event.type==="CLASE_CANCELADA"?`fue cancelada. Motivo: ${row.motivoCancelacion}`:`fue suspendida. Motivo: ${row.motivoCancelacion}`;await createNotifications(userIds.map(userId=>({userId,type:event.type,title:event.title,message:`La clase de ${scheduleInfo.actividad.nombre} del ${dateText(row.fecha)} ${eventMessage}`,priority:event.priority,actionUrl:"/citizen/schedule",actionLabel:"Ver próximas clases",entityType:"activity_session",entityId:row.id,deduplicationKey:`session-${event.type.toLowerCase()}:${row.id}:${userId}:${row.updatedAt.getTime()}`})),tx);}
  return map(row,await counts(tx,[row]));
});}
export const changeActivitySessionStatus=(id:string,status:ClaseActividadEstado)=>updateActivitySession(id,{status});
export async function listActivitySessions(filters:ActivitySessionFilters){const f=filters as any,search=f.search?.trim();const where:Prisma.ClaseActividadWhereInput={estado:f.status,horarioActividadId:f.activityScheduleId,establecimientoId:f.establishmentId,fecha:f.dateFrom||f.dateTo?{gte:f.dateFrom?dateValue(f.dateFrom):undefined,lte:f.dateTo?dateValue(f.dateTo):undefined}:undefined,horarioActividad:{actividadId:f.activityId},profesores:f.professorId?{some:{profesorId:f.professorId}}:undefined,...(search?{OR:[{espacio:{contains:search,mode:"insensitive"}},{establecimiento:{nombre:{contains:search,mode:"insensitive"}}},{horarioActividad:{actividad:{nombre:{contains:search,mode:"insensitive"}}}},{profesores:{some:{profesor:{usuario:{OR:[{nombre:{contains:search,mode:"insensitive"}},{apellido:{contains:search,mode:"insensitive"}}]}}}}}]}:{})};return prisma.$transaction(async tx=>{const[total,rows]=await Promise.all([tx.claseActividad.count({where}),tx.claseActividad.findMany({where,include,orderBy:[{fecha:"asc"},{horaInicio:"asc"}],skip:(f.page-1)*f.pageSize,take:f.pageSize})]),summary=await counts(tx,rows);return{items:rows.map(x=>map(x,summary)),meta:{total,page:f.page,pageSize:f.pageSize,pageCount:Math.max(1,Math.ceil(total/f.pageSize))}};});}
