import { axiosInstance } from "@/lib/axios";
import type { AttendanceFilters,AttendanceRoster, MarkAttendanceBatchInput } from "@/features/attendance/types/attendance.types";
import type { ActivitySession, ActivitySessionFilters } from "@/features/activity-sessions/types/activity-session.types";
import { workspaceEstablishmentStorageKey } from "@/features/auth/libs/workspaces";
import { useAuth } from "@/stores/auth";
export type TeacherEstablishment = { id: string; nombre: string; direccion: string };
const establishmentId = () => { const userId=useAuth.getState().user?.id; return userId && typeof window!=="undefined" ? sessionStorage.getItem(workspaceEstablishmentStorageKey(userId,"teacher")) ?? undefined : undefined; };
const venueParams = (params?:Record<string,string|number|undefined>) => ({...params,establishmentId:establishmentId()});
export const getTeacherEstablishmentsClient=async()=>(await axiosInstance.get<{data:TeacherEstablishment[]}>("/teacher/establishments")).data.data;
export const getTeacherClassesClient=async(params?:ActivitySessionFilters)=>(await axiosInstance.get<{data:ActivitySession[];meta:{total:number;page:number;pageSize:number;pageCount:number}}>("/teacher/classes",{params:venueParams(params as Record<string,string|number|undefined>)})).data;
export const getTeacherClassClient=async(id:string)=>(await axiosInstance.get<{data:ActivitySession}>(`/teacher/classes/${id}`,{params:venueParams()})).data.data;
export const suspendTeacherClassClient=async(id:string,reason:string)=>(await axiosInstance.post(`/teacher/classes/${id}/suspend`,{reason,establishmentId:establishmentId()})).data.data;
export const getTeacherSummaryClient=async()=>(await axiosInstance.get("/teacher/summary",{params:venueParams()})).data.data;
export const getTeacherSchedulesClient=async()=>(await axiosInstance.get("/teacher/schedules",{params:venueParams()})).data.data;
export const getTeacherSessionsClient=async(params?:AttendanceFilters)=>(await axiosInstance.get("/teacher/sessions",{params:venueParams(params as Record<string,string|number|undefined>)})).data;
export const getTeacherSessionClient=async(id:string)=>(await axiosInstance.get<{data:AttendanceRoster}>(`/teacher/sessions/${id}`,{params:venueParams()})).data.data;
export const getTeacherAttendanceClient=async(id:string)=>(await axiosInstance.get<{data:AttendanceRoster}>(`/teacher/attendance/${id}`,{params:venueParams(),showTeacherAssignmentError:true})).data.data;
export const updateTeacherAttendanceClient=async(id:string,data:{action:"batch";records:MarkAttendanceBatchInput["records"]}|{action:"close"}|{action:"reopen"})=>(await axiosInstance.post<{data:AttendanceRoster}>(`/teacher/attendance/${id}`,data,{params:venueParams()})).data.data;
export const registerTeacherQrClient=async(id:string,qrToken:string)=>(await axiosInstance.post(`/teacher/attendance/${id}/qr`,{qrToken})).data;
export const getTeacherNotificationsClient=async()=>(await axiosInstance.get("/teacher/notifications")).data.data;
export const getTeacherProfileClient=async()=>(await axiosInstance.get("/teacher/profile")).data.data;
export const updateTeacherProfileClient=async(data:{description?:string|null;photoUrl?:string|null})=>(await axiosInstance.patch("/teacher/profile",data)).data.data;
