"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CitizenCard, CitizenHeader, CitizenState } from "@/features/citizen/components/CitizenPrimitives";
import { MAX_ENROLLMENT_DOCUMENT_BYTES } from "../constants/file-rules";
import { useCitizenEnrollmentDocuments } from "../hooks/useEnrollmentDocuments";
import { downloadCitizenEnrollmentDocumentClient, removeCitizenEnrollmentDocumentClient, uploadCitizenEnrollmentDocumentClient } from "../services/enrollment-documents.service";
const summary: Record<string, string> = { NO_REQUERIDA: "No requiere documentación", PENDIENTE: "Documentación pendiente", EN_REVISION: "En revisión", OBSERVADA: "Documentación observada", COMPLETA: "Documentación completa" };
export function CitizenEnrollmentDocumentsPage({ id }: { id: string }) {
  const { data, loading, error, refresh } = useCitizenEnrollmentDocuments(id);
  const [files, setFiles] = useState<Record<string, File | null>>({});
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState("");
  async function upload(requirementId: string) { const file = files[requirementId]; if (!file) return; setSaving(requirementId); try { await uploadCitizenEnrollmentDocumentClient(id, requirementId, file, notes[requirementId]); toast.success("Documento enviado para revisión."); await refresh(); } catch { toast.error("No pudimos adjuntar el documento."); } finally { setSaving(""); } }
  return <div><CitizenHeader title="Documentos de la inscripción" description={data ? `${data.enrollment.activity.name} · ${summary[data.summary.status]}` : "Gestioná la documentación solicitada."}/><CitizenState loading={loading} error={error} onRetry={refresh}>{data ? <div className="mt-5 grid gap-4">{data.requirements.map((requirement: any) => <CitizenCard key={requirement.id}><h2 className="font-extrabold text-[var(--brand-primary)]">{requirement.name} · {requirement.mandatory ? "Obligatorio" : "Opcional"}</h2><p className="text-sm text-[var(--brand-muted)]">{requirement.instructions || "Sin instrucciones adicionales."}</p>{requirement.current ? <div className="mt-3 rounded-xl bg-[var(--brand-panel)] p-3"><p className="font-bold">{requirement.current.status === "PENDIENTE" ? "Pendiente de revisión" : requirement.current.status === "APROBADO" ? "Documento aprobado" : "Documento rechazado"}</p><p className="text-sm">{requirement.current.originalName} · versión {requirement.current.version}</p>{requirement.current.rejectionReason ? <p className="text-sm text-red-700">Motivo: {requirement.current.rejectionReason}</p> : null}<Button variant="link" onClick={() => void downloadCitizenEnrollmentDocumentClient(id, requirement.current.id).then((url) => window.open(url, "_blank", "noopener,noreferrer"))}>Descargar</Button>{requirement.current.status === "PENDIENTE" ? <Button variant="ghost" onClick={() => void removeCitizenEnrollmentDocumentClient(id, requirement.current.id).then(refresh)}>Retirar</Button> : null}</div> : null}{!requirement.current || requirement.current.status === "RECHAZADO" ? <div className="mt-4 space-y-3"><Input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(event) => setFiles((current) => ({ ...current, [requirement.id]: event.target.files?.[0] ?? null }))}/><p className="text-xs">PDF, JPG o PNG. Máximo {MAX_ENROLLMENT_DOCUMENT_BYTES / 1024 / 1024} MB.</p><Textarea placeholder="Observaciones (opcional)" value={notes[requirement.id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [requirement.id]: event.target.value }))}/><Button disabled={!Boolean(files[requirement.id]) || saving === requirement.id} onClick={() => void upload(requirement.id)}>{requirement.current ? "Adjuntar nueva versión" : "Adjuntar documento"}</Button></div> : null}</CitizenCard>)}</div> : null}</CitizenState></div>;
}
