"use client";

import Link from "next/link";
import { useState } from "react";
import { Bell, CheckCircle2, Home, Plus, UserPlus } from "lucide-react";
import { UserForm } from "@/features/users/components/UserForm";
import { Button } from "@/components/ui/button";
import { adminPrimaryButtonClass, adminSecondaryButtonClass } from "@/components/shared/admin-patterns";

function ReceptionRequestAccessMobileHeader() {
  return <header className="relative h-[174px] shrink-0 overflow-hidden md:hidden"><svg className="absolute inset-0 size-full" viewBox="0 0 440 190" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="mobile-reception-request-header" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#1D4F36"/><stop offset="72%" stopColor="#14543A"/><stop offset="100%" stopColor="#0B6843"/></linearGradient></defs><path d="M0 0H440V154C354 130 300 174 197 170C111 168 48 154 0 135V0Z" fill="url(#mobile-reception-request-header)"/></svg><span className="pointer-events-none absolute -left-3 top-[92px] h-16 w-12 rotate-[-22deg] rounded-[80%_15%_80%_15%] bg-[var(--brand-secondary)]/12" aria-hidden="true"/><span className="pointer-events-none absolute left-7 top-[110px] h-12 w-8 rotate-[30deg] rounded-[80%_15%_80%_15%] bg-white/[0.045]" aria-hidden="true"/><div className="relative z-10 flex items-center justify-between px-4 pt-[max(1rem,env(safe-area-inset-top))]"><Link href="/reception" className="min-w-0"><span className="min-w-0 drop-shadow-sm"><strong className="block truncate text-base tracking-wide text-white">MÁS SAN MIGUEL</strong><span className="mt-0.5 block text-sm font-medium text-white/90">Portal de Recepción</span></span></Link><Link href="/reception/notifications" aria-label="Notificaciones" className="grid size-10 place-items-center rounded-xl bg-white/15 text-white backdrop-blur"><Bell className="size-5"/></Link></div></header>;
}

export function ReceptionRequestAccessPage() {
  const [completed, setCompleted] = useState(false);
  if (completed) return <main className="min-h-[calc(100dvh-var(--topbar-h)-48px)] bg-[var(--brand-page)] p-4 sm:p-6 lg:p-8"><section className="mx-auto flex min-h-[480px] max-w-2xl flex-col items-center justify-center rounded-3xl border border-[var(--brand-border-soft)] bg-white p-8 text-center shadow-sm"><span className="grid size-16 place-items-center rounded-2xl bg-[var(--brand-border-soft)] text-[var(--brand-primary)]"><CheckCircle2 className="size-9" /></span><h1 className="mt-5 text-3xl font-extrabold text-[var(--brand-primary)]">Solicitud enviada</h1><p className="mt-3 max-w-md text-[var(--brand-muted)]">La solicitud de acceso quedó pendiente de revisión por un administrador.</p><div className="mt-8 flex w-full flex-col gap-3 sm:flex-row sm:justify-center"><Button type="button" className={adminPrimaryButtonClass} onClick={() => setCompleted(false)}><Plus />Crear otra solicitud</Button><Button asChild variant="outline" className={adminSecondaryButtonClass}><Link href="/reception"><Home />Volver al Dashboard</Link></Button></div></section></main>;

  return <><ReceptionRequestAccessMobileHeader/><main className="min-h-[calc(100dvh-var(--topbar-h)-48px)] w-full overflow-y-auto bg-[var(--brand-page)] px-3 py-5 sm:p-6 lg:p-8"><header className="relative z-10 mb-5 pt-1 text-center md:hidden"><h1 className="text-3xl font-extrabold text-[var(--brand-primary)]">Solicitar acceso</h1><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[var(--brand-muted)]">Cargá tus datos personales, la foto y las credenciales de acceso.</p></header><UserForm mode="create" submissionMode="reception-request" fixedRoleCode="citizen" backHref="/reception/citizens" title="Solicitar acceso" description="Cargá los datos de la persona para enviar una solicitud de acceso al portal." headerIcon={UserPlus} submitLabel="Enviar solicitud" onSuccess={() => setCompleted(true)} mobileRequestAccess /></main></>;
}
