"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Building2, CalendarClock, ChevronRight, Clock3, Edit3, Eye, MapPin, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AdminDetailActions, AdminDetailHeader, AdminDetailPanel, AdminListCard } from "@/components/shared/admin-patterns";
import { CatalogDetailField, CatalogEmptyState, CatalogFilterPopover, CatalogLoadingState, CatalogPageHeader, CatalogPagination, CatalogSearchInput, CATALOG_PAGE_SIZE } from "@/features/activity-catalogs/components/CatalogPrimitives";
import { useCan } from "@/hooks/useCan";
import { cn } from "@/lib/utils";
import { useActivitySchedules } from "../hooks/useActivitySchedules";
import { dayLabel, statusLabel } from "../helpers/activity-schedule-display";
import type { ActivitySchedule, ActivityScheduleStatus, WeekDay } from "../types/activity-schedule.types";

export function ActivitySchedulesPage() {
  const router = useRouter(), params = useSearchParams();
  const [search, setSearch] = useState(""), [day, setDay] = useState("all"), [status, setStatus] = useState("all"), [activity, setActivity] = useState(params.get("activityId") ?? "all"), [establishment, setEstablishment] = useState(params.get("establishmentId") ?? "all"), [professor, setProfessor] = useState("all"), [page, setPage] = useState(1), [selectedId, setSelectedId] = useState(params.get("selected") ?? "");
  const filters = useMemo(() => ({ search: search || undefined, day: day === "all" ? undefined : day as WeekDay, status: status === "all" ? undefined : status as ActivityScheduleStatus, activityId: activity === "all" ? undefined : activity, establishmentId: establishment === "all" ? undefined : establishment, professorId: professor === "all" ? undefined : professor }), [search, day, status, activity, establishment, professor]);
  const { data, loading, error, refresh } = useActivitySchedules(filters), selected = data.find((item) => item.id === selectedId) ?? null;
  const pageItems = data.slice((page - 1) * CATALOG_PAGE_SIZE, page * CATALOG_PAGE_SIZE), activities = unique(data.map((item) => [item.activity.id, item.activity.name])), establishments = unique(data.map((item) => [item.establishment.id, item.establishment.name])), professors = unique(data.flatMap((item) => item.professors.map((entry) => [entry.id, entry.fullName])));
  useEffect(() => setPage(1), [search, day, status, activity, establishment, professor]);
  if (loading) return <CatalogLoadingState label="horarios de actividades" fullPage />;
  return <main className="min-h-full bg-[var(--brand-page)] p-4 sm:p-6 lg:p-8"><CatalogPageHeader icon={CalendarClock} title="Horarios de actividades" description="Consultá y ajustá operativamente la programación semanal creada desde el workflow de actividades." total={data.length} />
    <section className="mt-6 grid min-h-0 gap-6 lg:grid-cols-[minmax(340px,.95fr)_minmax(420px,1.05fr)]"><div className={cn("min-h-0 flex-col gap-4", selectedId ? "hidden lg:flex" : "flex")}><div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><CatalogSearchInput value={search} onChange={setSearch} placeholder="Buscar por actividad, sede, espacio o profesor..." /><CatalogFilterPopover sections={[{ id:"activity", title:"Actividad", value:activity, options:[["all","Todas"],...activities].map(([value,label])=>({value,label})), onChange:setActivity },{ id:"establishment", title:"Establecimiento", value:establishment, options:[["all","Todos"],...establishments].map(([value,label])=>({value,label})), onChange:setEstablishment },{ id:"professor", title:"Profesor", value:professor, options:[["all","Todos"],...professors].map(([value,label])=>({value,label})), onChange:setProfessor },{ id:"day", title:"Día", value:day, options:[["all","Todos"],["LUNES","Lunes"],["MARTES","Martes"],["MIERCOLES","Miércoles"],["JUEVES","Jueves"],["VIERNES","Viernes"],["SABADO","Sábado"],["DOMINGO","Domingo"]].map(([value,label])=>({value,label})), onChange:setDay },{ id:"status", title:"Estado", value:status, options:[["all","Todos"],["ACTIVO","Activo"],["SUSPENDIDO","Suspendido"],["CANCELADO","Cancelado"],["FINALIZADO","Finalizado"]].map(([value,label])=>({value,label})), onChange:setStatus }]} /></div>
      {error ? <div className="rounded-2xl border border-[var(--brand-border)] bg-white p-5">No pudimos cargar los horarios. <Button onClick={() => void refresh()}>Reintentar</Button></div> : !data.length ? <CatalogEmptyState title="No se encontraron horarios." description="Los horarios aparecerán cuando una actividad complete su workflow de configuración." filtered={Boolean(search) || [day,status,activity,establishment,professor].some((value)=>value!=="all")} /> : <div className="flex min-h-0 flex-col gap-3"><div className="grid gap-3 overflow-y-auto pr-1 lg:max-h-[calc(100dvh-var(--topbar-h)-310px)]">{pageItems.map((item)=><AdminListCard key={item.id} onClick={()=>setSelectedId(item.id)} selected={selectedId===item.id} leading={<span className="grid size-12 place-items-center rounded-xl bg-[var(--brand-primary)] text-white"><CalendarClock className="size-6" /></span>} title={`${dayLabel(item.day)} · ${item.startTime} a ${item.endTime}`} badges={<ScheduleStatus status={item.status} />} description={<span className="flex items-center gap-1 truncate"><Building2 className="size-3.5" />{item.activity.name} · {item.establishment.name}</span>} meta={`${item.professors.map((entry)=>entry.fullName).join(", ") || "Sin profesor"} · Cupo ${item.maxCapacity}`} trailing={<ChevronRight className="size-5" />} />)}</div><CatalogPagination page={page} total={data.length} onPageChange={setPage} /></div>}
    </div><div className={cn(!selectedId && "hidden lg:block")}><ScheduleDetail item={selected} onBack={()=>setSelectedId("")} onEdit={(id)=>router.push(`/activity-schedules/${id}/edit`)} onRecord={(id)=>router.push(`/activity-schedules/${id}/record/overview`)} /></div></section></main>;
}

function ScheduleDetail({ item, onBack, onEdit, onRecord }: { item: ActivitySchedule | null; onBack:()=>void; onEdit:(id:string)=>void; onRecord:(id:string)=>void }) {
  const canEdit = useCan("activity_schedules", "editar");
  if (!item) return <AdminDetailPanel empty="Seleccioná un horario para consultar su detalle." />;
  return <AdminDetailPanel onBack={onBack}><AdminDetailHeader title={item.activity.name} leading={<span className="grid size-16 place-items-center rounded-2xl bg-[var(--brand-primary)] text-white"><CalendarClock className="size-8" /></span>} badge={<ScheduleStatus status={item.status} />} action={<Button variant="outline" onClick={()=>onRecord(item.id)} className="w-full border-[var(--brand-secondary)] bg-white font-bold text-[var(--brand-primary)]"><Eye />Ver ficha completa</Button>} /><dl className="mt-6 grid gap-3"><CatalogDetailField icon={Clock3} label="Día y horario">{dayLabel(item.day)} · {item.startTime} a {item.endTime}</CatalogDetailField><CatalogDetailField icon={MapPin} label="Establecimiento">{item.establishment.name}</CatalogDetailField><CatalogDetailField icon={Building2} label="Espacio">{item.space || "Sin espacio informado"}</CatalogDetailField><CatalogDetailField icon={UsersRound} label="Cupo">{item.maxCapacity} personas</CatalogDetailField></dl>{canEdit ? <AdminDetailActions><Button onClick={()=>onEdit(item.id)} className="bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)]"><Edit3 />Ajustar operación</Button></AdminDetailActions> : null}</AdminDetailPanel>;
}
function ScheduleStatus({ status }: { status: ActivityScheduleStatus }) { return <Badge variant="outline" className="border-[var(--brand-secondary)]/40 bg-[var(--brand-secondary)]/15 text-[var(--brand-primary)]">{statusLabel(status)}</Badge>; }
function unique(values:string[][]){return [...new Map(values.map((item)=>[item[0],item])).values()];}
