"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Boxes, Building2, CalendarClock, Check, FileText, Loader2, Save, UserRound, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AdminDetailHeader, adminPrimaryButtonClass } from "@/components/shared/admin-patterns";
import { CatalogDetailField, CatalogLoadingState } from "@/features/activity-catalogs/components/CatalogPrimitives";
import { listarProfesoresClient } from "@/features/profesores/services/profesores.service";
import { listResourcesClient } from "@/features/resources/services/resources.service";
import { updateActivityScheduleSchema, SCHEDULE_STATUSES } from "../schemas/activity-schedule.schema";
import { updateActivityScheduleClient } from "../services/activity-schedules.service";
import { dayLabel, statusLabel } from "../helpers/activity-schedule-display";
import type { ActivitySchedule } from "../types/activity-schedule.types";

export function ActivityScheduleForm({ initialValues, onLoadingChange }: { initialValues?:ActivitySchedule; onLoadingChange?:(value:boolean)=>void }) {
  const router=useRouter(),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[options,setOptions]=useState<any>({professors:[],resources:[]});
  const [form,setForm]=useState<any>({estado:initialValues?.status??"ACTIVO",espacio:initialValues?.space??"",observaciones:initialValues?.notes??"",cupoMaximo:initialValues?.maxCapacity??1,permiteListaEspera:initialValues?.waitingListEnabled??true,permiteSobrecupo:initialValues?.overbookingEnabled??false,sobrecupoMaximo:initialValues?.overbookingLimit??null,profesoresIds:initialValues?.professors.map((item)=>item.id)??[],profesorPrincipalId:initialValues?.professors.find((item)=>item.isPrimary)?.id??null,recursos:initialValues?.resources.map((item)=>({recursoId:item.resourceId,cantidadReservada:item.quantity,estrategiaAsignacion:item.assignmentStrategy,exclusivo:item.exclusive}))??[]});
  useEffect(()=>{let active=true;void Promise.all([listarProfesoresClient({page:1,pageSize:100,estado:"ACTIVO"}),listResourcesClient()]).then(([professors,resources])=>{if(active)setOptions({professors:professors.data.filter((item)=>item.usuario.rol.codigo==="teacher"),resources:resources.filter((item:any)=>item.establecimientoId===initialValues?.establishmentId&&(item.estado==="ACTIVO"||form.recursos.some((entry:any)=>entry.recursoId===item.id)))})}).catch(()=>toast.error("No pudimos cargar profesores y recursos.")).finally(()=>active&&setLoading(false));return()=>{active=false};},[initialValues?.establishmentId]);
  useEffect(()=>onLoadingChange?.(loading),[loading,onLoadingChange]);
  if(!initialValues)return <div className="rounded-3xl border border-[#DDE8D7] bg-white p-8 text-center"><p className="font-extrabold text-[#1D4F36]">Los horarios se crean desde el workflow de actividades.</p><Button className="mt-4" onClick={()=>router.replace("/activities")}>Ir a actividades</Button></div>;
  if(loading)return <CatalogLoadingState label="ajustes operativos del horario"/>;
  const set=(key:string,value:any)=>setForm((current:any)=>({...current,[key]:value}));
  async function submit(event:React.FormEvent){event.preventDefault();const payload={...form,espacio:form.espacio.trim()||null,observaciones:form.observaciones.trim()||null,sobrecupoMaximo:form.permiteSobrecupo?form.sobrecupoMaximo:null};const parsed=updateActivityScheduleSchema.safeParse(payload);if(!parsed.success){toast.error(parsed.error.issues[0]?.message??"Revisá los datos.");return}setSaving(true);try{await updateActivityScheduleClient(initialValues!.id,parsed.data);toast.success("Ajustes operativos guardados.");router.replace(`/activity-schedules?selected=${initialValues!.id}`)}catch(error:any){toast.error(error?.response?.data?.message??"No pudimos guardar los cambios.")}finally{setSaving(false)}}
  return <form onSubmit={submit} className="space-y-6"><div className="rounded-3xl border border-[var(--brand-border-soft)] bg-white p-5 shadow-sm sm:p-7"><AdminDetailHeader title={initialValues.activity.name} leading={<span className="grid size-16 place-items-center rounded-2xl bg-[var(--brand-primary)] text-white"><CalendarClock className="size-8"/></span>} badge={<span className="rounded-full border border-[#819B56]/40 bg-[#819B56]/15 px-3 py-1 text-xs font-bold text-[#1D4F36]">Ajuste operativo</span>} /><div className="mt-6 grid gap-3 sm:grid-cols-2"><CatalogDetailField icon={CalendarClock} label="Día y franja definidos en el workflow">{dayLabel(initialValues.day)} · {initialValues.startTime} a {initialValues.endTime}</CatalogDetailField><CatalogDetailField icon={Building2} label="Establecimiento definido en el workflow">{initialValues.establishment.name}</CatalogDetailField></div>
    <Section title="Operación" icon={CalendarClock}><Grid><Control label="Estado" icon={Check}><Select value={form.estado} onValueChange={(value)=>set("estado",value)}><SelectTrigger className="control"><SelectValue/></SelectTrigger><SelectContent>{SCHEDULE_STATUSES.map((item)=><SelectItem key={item} value={item}>{statusLabel(item)}</SelectItem>)}</SelectContent></Select></Control><Control label="Espacio" icon={Building2}><Input value={form.espacio} onChange={(event)=>set("espacio",event.target.value)} placeholder="Ej. Cancha 2"/></Control><Control label="Cupo máximo" icon={UsersRound}><Input type="number" min={1} value={form.cupoMaximo} onChange={(event)=>set("cupoMaximo",Number(event.target.value))}/></Control><Toggle label="Permite lista de espera" checked={form.permiteListaEspera} onChange={(value)=>set("permiteListaEspera",value)}/><Toggle label="Permite sobrecupo" checked={form.permiteSobrecupo} onChange={(value)=>set("permiteSobrecupo",value)}/>{form.permiteSobrecupo?<Control label="Sobrecupo máximo" icon={UsersRound}><Input type="number" min={1} value={form.sobrecupoMaximo??""} onChange={(event)=>set("sobrecupoMaximo",Number(event.target.value))}/></Control>:null}</Grid></Section>
    <Section title="Profesores" icon={UserRound}><div className="grid gap-3 sm:grid-cols-2">{options.professors.map((professor:any)=>{const checked=form.profesoresIds.includes(professor.id);return <label key={professor.id} className={`flex items-center gap-3 rounded-xl border p-4 ${checked?"border-[#819B56] bg-[#EEF6E9]":"border-[#DDE8D7] bg-[#F7FBF5]"}`}><Checkbox checked={checked} onCheckedChange={(value)=>{const ids=value?[...new Set([...form.profesoresIds,professor.id])]:form.profesoresIds.filter((id:string)=>id!==professor.id);set("profesoresIds",ids);if(!value&&form.profesorPrincipalId===professor.id)set("profesorPrincipalId",null)}}/><span className="min-w-0 flex-1 text-sm font-bold">{professor.usuario.nombre} {professor.usuario.apellido}</span>{checked?<input type="radio" name="principal" checked={form.profesorPrincipalId===professor.id} onChange={()=>set("profesorPrincipalId",professor.id)} title="Profesor principal"/>:null}</label>})}</div></Section>
    <Section title="Recursos físicos" icon={Boxes}><div className="grid gap-3 sm:grid-cols-2">{options.resources.map((resource:any)=>{const entry=form.recursos.find((item:any)=>item.recursoId===resource.id);return <div key={resource.id} className={`rounded-xl border p-4 ${entry?"border-[#819B56] bg-[#EEF6E9]":"border-[#DDE8D7] bg-[#F7FBF5]"}`}><label className="flex items-center gap-3"><Checkbox checked={Boolean(entry)} onCheckedChange={(value)=>set("recursos",value?[...form.recursos,{recursoId:resource.id,cantidadReservada:1,estrategiaAsignacion:"AL_INGRESAR",exclusivo:false}]:form.recursos.filter((item:any)=>item.recursoId!==resource.id))}/><span className="font-bold">{resource.nombre}</span></label>{entry?<Input className="mt-3" type="number" min={1} max={resource.capacidadUnidades} value={entry.cantidadReservada} onChange={(event)=>set("recursos",form.recursos.map((item:any)=>item.recursoId===resource.id?{...item,cantidadReservada:Number(event.target.value)}:item))}/>:null}</div>})}{!options.resources.length?<p className="text-sm text-[#5F6F68]">No hay recursos disponibles para esta sede.</p>:null}</div></Section>
    <Section title="Observaciones" icon={FileText}><Control label="Información operativa" icon={FileText}><Textarea rows={4} value={form.observaciones} onChange={(event)=>set("observaciones",event.target.value)}/></Control></Section>
  </div><div className="flex justify-end border-t border-[var(--brand-border)] pt-5"><Button size="lg" disabled={saving} className={adminPrimaryButtonClass}>{saving?<Loader2 className="animate-spin"/>:<Save/>}Guardar ajustes</Button></div></form>;
}
function Section({title,icon:Icon,children}:{title:string;icon:typeof CalendarClock;children:React.ReactNode}){return <section className="mt-6 border-t border-[#DDE8D7] pt-6"><div className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#DDE8D7] text-[#1D4F36]"><Icon className="size-5"/></span><h2 className="text-lg font-extrabold text-[#1D4F36]">{title}</h2></div>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-5 sm:grid-cols-2">{children}</div>}
function Control({label,icon:Icon,children}:{label:string;icon:typeof CalendarClock;children:React.ReactNode}){return <div className="space-y-2"><Label className="font-bold text-[#173C2A]">{label}</Label><div className="relative"><Icon className="pointer-events-none absolute left-3.5 top-3.5 z-10 size-5 text-[#1D4F36]"/><div className="[&_input]:h-12 [&_input]:rounded-xl [&_input]:border-[#C9D9C3] [&_input]:bg-[#F7FBF5] [&_input]:pl-11 [&_button]:h-12 [&_button]:w-full [&_button]:rounded-xl [&_button]:border-[#C9D9C3] [&_button]:bg-[#F7FBF5] [&_button]:pl-11 [&_textarea]:rounded-xl [&_textarea]:border-[#C9D9C3] [&_textarea]:bg-[#F7FBF5] [&_textarea]:pl-11">{children}</div></div></div>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex h-12 items-center gap-3 self-end rounded-xl border border-[#C9D9C3] bg-[#F7FBF5] px-4"><Checkbox checked={checked} onCheckedChange={(value)=>onChange(value===true)}/><span className="font-bold text-[#173C2A]">{label}</span></label>}
