import { z } from "zod";

export const ACTIVITY_SESSION_STATUSES = ["PROGRAMADA", "EN_CURSO", "FINALIZADA", "SUSPENDIDA", "CANCELADA"] as const;
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Usá el formato YYYY-MM-DD").refine((value) => !Number.isNaN(Date.parse(`${value}T00:00:00Z`)), "Fecha inválida");
const time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Usá el formato HH:mm");
const fields = z.object({ activityScheduleId:z.string().min(1),date,startTime:time.optional(),endTime:time.optional(),establishmentId:z.string().min(1).optional(),space:z.string().trim().max(120).nullable().optional(),capacity:z.coerce.number().int().positive().nullable().optional(),cancellationReason:z.string().trim().min(3).max(500).nullable().optional(),professorIds:z.array(z.string().uuid()).optional(),primaryProfessorId:z.string().uuid().nullable().optional(),status:z.enum(ACTIVITY_SESSION_STATUSES).optional(),observations:z.string().trim().max(1000).nullable().optional() });
function coherent(value:z.infer<typeof fields>,ctx:z.RefinementCtx){if(value.startTime&&value.endTime&&value.startTime>=value.endTime)ctx.addIssue({code:"custom",path:["endTime"],message:"La hora final debe ser posterior"});if(value.professorIds&&new Set(value.professorIds).size!==value.professorIds.length)ctx.addIssue({code:"custom",path:["professorIds"],message:"No repitas profesores"});if(value.primaryProfessorId&&value.professorIds&&!value.professorIds.includes(value.primaryProfessorId))ctx.addIssue({code:"custom",path:["primaryProfessorId"],message:"El principal debe estar seleccionado"});}
export const createActivitySessionSchema=fields.superRefine(coherent);
export const updateActivitySessionSchema=z.object({}).passthrough().refine(v=>Object.keys(v).length>0,"No se informaron cambios").pipe(fields.omit({activityScheduleId:true,date:true}).partial());
export const generateActivitySessionsSchema=z.object({activityScheduleId:z.string().min(1),dateFrom:date,dateTo:date,excludedDates:z.array(date).default([])}).superRefine((v,ctx)=>{const from=new Date(`${v.dateFrom}T00:00:00Z`),to=new Date(`${v.dateTo}T00:00:00Z`);if(from>to)ctx.addIssue({code:"custom",path:["dateTo"],message:"El rango es inválido"});if((to.getTime()-from.getTime())/86400000>184)ctx.addIssue({code:"custom",path:["dateTo"],message:"El rango máximo es de seis meses"});for(const x of v.excludedDates)if(x<v.dateFrom||x>v.dateTo)ctx.addIssue({code:"custom",path:["excludedDates"],message:"Las exclusiones deben estar dentro del rango"});});
export const activitySessionFiltersSchema=z.object({search:z.string().optional(),status:z.enum(ACTIVITY_SESSION_STATUSES).optional(),activityId:z.string().optional(),activityScheduleId:z.string().optional(),establishmentId:z.string().optional(),professorId:z.string().uuid().optional(),dateFrom:date.optional(),dateTo:date.optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(8)});
