"use client";

import Link from "next/link";
import { Bell, Building2, ChevronDown, ChevronRight, FileUp, History, MapPin, QrCode, Search, Send, UserRound, Zap, type LucideIcon } from "lucide-react";
import { UserAvatar } from "@/components/layout/user-menu/UserAvatar";
import type { WorkspaceEstablishment } from "@/features/workspace-establishment/WorkspaceEstablishmentProvider";
import type { ReceptionDashboardData } from "../../types/reception-dashboard.types";
import { useAuth } from "@/stores/auth";

const quickActions: Array<{href:string;label:string;icon:LucideIcon}> = [
  {href:"/reception/scan",label:"Escanear QR",icon:QrCode},
  {href:"/reception/manual",label:"Búsqueda manual",icon:Search},
  {href:"/reception/request-access",label:"Solicitar acceso",icon:Send},
  {href:"/reception/documents/new",label:"Adjuntar documentos",icon:FileUp},
  {href:"/reception/notifications",label:"Notificaciones",icon:Bell},
  {href:"/reception/history",label:"Historial",icon:History},
];

export function ReceptionMobileDashboard({data,loading,establishment,pendingRequests,unreadNotifications}:{data:ReceptionDashboardData|null;loading:boolean;establishment?:WorkspaceEstablishment;pendingRequests:number;unreadNotifications:number}){
  const user=useAuth(state=>state.user);
  const fullName=[user?.nombre,user?.apellido].filter(Boolean).join(" ")||user?.userId||"Recepción";
  const firstName=user?.nombre||"Recepción";
  return <div className="min-h-full overflow-x-hidden bg-[var(--brand-page)] pb-5">
    <header data-reception-mobile-header className="bg-[var(--brand-primary)] pt-[env(safe-area-inset-top)] text-white"><div className="flex h-20 items-center justify-between gap-3 px-4"><Link href="/reception" className="min-w-0" aria-label="MÁS San Miguel - Inicio"><span className="min-w-0 leading-tight"><strong className="block truncate text-sm tracking-wide">MÁS SAN MIGUEL</strong><span className="block text-xs text-white/85">Portal de Recepción</span></span></Link><Link href="/reception/notifications" className="relative grid size-11 shrink-0 place-items-center rounded-xl bg-white/10 text-white active:scale-95" aria-label={unreadNotifications?`${unreadNotifications} notificaciones sin leer`:"Notificaciones"}><Bell className="size-5"/>{unreadNotifications?<span className="absolute -right-1 -top-1 grid min-h-5 min-w-5 place-items-center rounded-full border-2 border-[var(--brand-primary)] bg-[var(--brand-accent)] px-1 text-[10px] font-extrabold text-[var(--brand-primary)]">{unreadNotifications>9?"9+":unreadNotifications}</span>:null}</Link></div></header>
    <section className="grid gap-3 px-4 py-5 min-[390px]:grid-cols-[minmax(0,1fr)_minmax(145px,.9fr)] min-[390px]:items-center"><div className="flex min-w-0 items-center gap-3"><UserAvatar src={user?.avatarUrl??undefined} name={fullName} className="size-14 shrink-0 rounded-full border-2 border-white shadow-md ring-1 ring-[var(--brand-border-soft)]" imageClassName="size-full rounded-full object-cover" fallbackBgClass="rounded-full bg-[var(--brand-panel)]" textClass="font-extrabold text-[var(--brand-primary)]"/><div className="min-w-0"><h1 className="truncate text-xl font-extrabold text-[var(--brand-primary)]">Hola, {firstName}</h1><Link href="/select-venue?workspace=reception&next=%2Freception" className="mt-1 flex min-w-0 items-center gap-1 text-xs text-[var(--brand-ink)]"><MapPin className="size-4 shrink-0 text-[var(--brand-primary)]"/><span className="truncate">{establishment?.nombre||data?.establishment.name||"Seleccionar establecimiento"}</span><ChevronDown className="size-4 shrink-0"/></Link></div></div><Link href="/select-venue?workspace=reception&next=%2Freception" className="flex min-w-0 items-center gap-2.5 rounded-2xl border border-[var(--brand-border-soft)] bg-white p-3 shadow-sm"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[var(--brand-primary)] text-white"><Building2 className="size-5"/></span><span className="min-w-0 flex-1"><span className="block text-[9px] font-bold text-[var(--brand-primary)]">Establecimiento elegido</span><strong className="mt-1 block truncate text-xs text-[var(--brand-ink)]">{establishment?.nombre||data?.establishment.name||"Seleccionar"}</strong><span className="mt-0.5 block truncate text-[10px] text-[var(--brand-muted)]">{establishment?.direccion||"Dirección no informada"}</span></span><ChevronRight className="size-4 shrink-0 text-[var(--brand-secondary)]"/></Link></section>
    {loading?<section className="mt-4 grid grid-cols-3 gap-2 px-4" aria-label="Cargando métricas">{[0,1,2].map(item=><div key={item} className="h-28 animate-pulse rounded-2xl border border-[var(--brand-border-soft)] bg-white"/>)}</section>:<section className="mt-4 grid grid-cols-3 gap-2 px-4"><Metric label="Ingresos hoy" value={data?.metrics.totalEntries??0} unit="personas" icon={UserRound}/><Metric label="Solicitudes pendientes" value={pendingRequests} unit="solicitudes" icon={Send}/><Metric label="Notificaciones" value={unreadNotifications} unit="nuevas" icon={Bell}/></section>}
    <section className="mt-6"><h2 className="mb-3 flex items-center gap-2 px-4 font-extrabold text-[var(--brand-primary)]"><Zap className="size-5 fill-current"/>Acciones rápidas</h2><div className="grid grid-cols-3 gap-2 px-4">{quickActions.map(({href,label,icon:Icon})=><Link key={href} href={href} className="flex min-h-24 min-w-0 flex-col items-center justify-center rounded-2xl border border-[var(--brand-border-soft)] bg-[#F9FAF5] px-1 py-2 text-center text-[9px] font-bold leading-3 text-[var(--brand-ink)] shadow-sm"><span className="mb-2 grid size-8 place-items-center text-[var(--brand-primary)]"><Icon className="size-6"/></span>{label}</Link>)}</div></section>
    <section className="mt-6 px-4"><h2 className="mb-3 flex items-center gap-2 font-extrabold text-[var(--brand-primary)]"><History className="size-5"/>Actividad reciente</h2>{loading?<div className="grid gap-2" aria-label="Cargando actividad reciente">{[0,1,2].map(item=><div key={item} className="h-16 animate-pulse rounded-2xl border border-[var(--brand-border-soft)] bg-white"/>)}</div>:data?.recentAccesses.length?<div className="grid gap-2">{data.recentAccesses.map(item=><Link key={item.id} href={`/reception/${item.id}`} className="flex min-w-0 items-center gap-3 rounded-2xl border border-[var(--brand-border-soft)] bg-white p-3 shadow-sm"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--brand-panel)] text-[var(--brand-primary)]"><History className="size-5"/></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-[var(--brand-ink)]">{item.personName??"Persona no identificada"}</strong><span className="mt-0.5 block truncate text-[10px] text-[var(--brand-muted)]">{item.documentNumber?`DNI ${item.documentNumber} · `:""}{new Date(item.occurredAt).toLocaleString("es-AR")}</span></span><span className={`shrink-0 text-[9px] font-bold ${item.result==="PERMITIDO"?"text-[var(--brand-primary)]":"text-red-700"}`}>{item.result==="PERMITIDO"?"Completado":"Rechazado"}</span></Link>)}</div>:<p className="rounded-2xl border border-dashed border-[var(--brand-border-soft)] bg-white p-5 text-center text-sm text-[var(--brand-muted)]">No hay actividad reciente en este establecimiento.</p>}</section>
  </div>;
}

function Metric({label,value,unit,icon:Icon}:{label:string;value:number;unit:string;icon:LucideIcon}){return <div className="flex min-h-24 min-w-0 flex-col rounded-2xl border border-[var(--brand-border-soft)] bg-[#F9FAF5] p-2.5 shadow-[0_8px_20px_rgba(29,79,54,0.12)]"><span className="text-[12px] font-extrabold leading-[14px] text-[var(--brand-ink)]">{label}</span><div className="mt-auto flex items-end justify-between gap-1"><span className="grid size-8 shrink-0 place-items-center rounded-xl bg-[var(--brand-panel)] text-[var(--brand-primary)]"><Icon className="size-4.5"/></span><span className="min-w-0 text-right"><strong className="block text-3xl leading-none text-[var(--brand-primary)]">{value}</strong><span className="block truncate text-[8px] leading-3 text-[var(--brand-muted)]">{unit}</span></span></div></div>}
