"use client";
import Link from "next/link";
import { useEffect,useState,type ReactNode } from "react";
import { Bell,Building2,CalendarCheck,CalendarClock,CalendarDays,ChevronRight,ClipboardCheck,History,UserRound,type LucideIcon } from "lucide-react";
import { AdminPageShell,AdminSectionHeader } from "@/components/shared/admin-patterns";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { CatalogEmptyState,CatalogErrorState,CatalogLoadingState,CatalogPageHeader } from "@/features/activity-catalogs/components/CatalogPrimitives";
import { useWorkspaceEstablishment } from "@/features/workspace-establishment/WorkspaceEstablishmentProvider";
import { getTeacherSummaryClient } from "../services/teacher.service";
import { TeacherMobileDashboard } from "./mobile/TeacherMobileDashboard";
export type TeacherSummarySession={id:string;date:string;startTime:string;endTime:string;activityName:string;activityImageUrl:string|null;establishmentName:string;space:string|null;status:string;confirmedCount:number};
export type TeacherSummary={todaySessions:number;upcomingSessions:number;pendingRosters:number;unreadCount:number;schedulesChanged:number;todayClasses:TeacherSummarySession[];nextSession:TeacherSummarySession|null};
type Summary=TeacherSummary;
export function TeacherDashboard(){const establishment=useWorkspaceEstablishment(),[data,setData]=useState<TeacherSummary|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false);function load(){setLoading(true);setError(false);void getTeacherSummaryClient().then(result=>setData(result as TeacherSummary)).catch(()=>setError(true)).finally(()=>setLoading(false))}useEffect(load,[]);if(loading)return <><div className="md:hidden"><CatalogLoadingState label="resumen docente" fullPage/></div><div className="hidden md:block"><AdminPageShell><CatalogLoadingState label="resumen docente"/></AdminPageShell></div></>;if(error||!data)return <><div className="md:hidden"><CatalogErrorState message="No pudimos cargar el resumen docente." onRetry={load}/></div><div className="hidden md:block"><AdminPageShell><CatalogErrorState message="No pudimos cargar el resumen docente." onRetry={load}/></AdminPageShell></div></>;return <><div className="md:hidden"><TeacherMobileDashboard data={data}/></div><div className="hidden md:block"><AdminPageShell><CatalogPageHeader icon={CalendarCheck} title="Dashboard del Profesor" description="Resumen docente del establecimiento, tus clases y tareas pendientes." total={data.todaySessions}/><Card className="mt-6 rounded-2xl border-[var(--brand-border-soft)] bg-white shadow-sm"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex min-w-0 items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[var(--brand-border-soft)] text-[var(--brand-primary)]"><Building2 className="size-5"/></span><div><h2 className="font-extrabold text-[var(--brand-primary)]">Establecimiento de trabajo</h2><p className="mt-1 text-sm text-[var(--brand-muted)]">Consultá y gestioná tu actividad docente en la sede seleccionada.</p></div></div><Select value={establishment.establishmentId} onValueChange={establishment.setEstablishmentId}><SelectTrigger className="h-11 w-full rounded-xl border-[var(--brand-border)] bg-[var(--brand-control)] sm:w-80"><SelectValue placeholder="Seleccionar establecimiento"/></SelectTrigger><SelectContent>{establishment.options.map(item=><SelectItem key={item.id} value={item.id}>{item.nombre}</SelectItem>)}</SelectContent></Select></CardContent></Card><DashboardContent data={data}/></AdminPageShell></div></>}
function DashboardContent({data}:{data:Summary}){const metrics:[[string,number,LucideIcon,string],[string,number,LucideIcon,string],[string,number,LucideIcon,string],[string,number,LucideIcon,string]]=[["Clases de hoy",data.todaySessions,CalendarDays,"Programación del día"],["Planillas pendientes",data.pendingRosters,ClipboardCheck,"Requieren registro"],["Notificaciones no leídas",data.unreadCount,Bell,"Comunicaciones nuevas"],["Horarios con novedades",data.schedulesChanged,CalendarClock,"Cambios de programación"]];return <><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon,subtitle])=><Metric key={label} label={label} value={value} icon={Icon} subtitle={subtitle}/>)}</section><section className="mt-6 grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Panel icon={CalendarCheck} title="Accesos rápidos" description="Herramientas habituales de tu experiencia docente."><div className="grid gap-3"><QuickAction href="/teacher/classes" icon={CalendarDays} label="Ver clases" description="Consultar clases asignadas y sus detalles."/><QuickAction href="/teacher/attendance" icon={ClipboardCheck} label="Ver asistencias" description="Abrir planillas habilitadas y registrar asistencia."/><QuickAction href="/teacher/profile" icon={UserRound} label="Mi perfil" description="Consultar y actualizar tus datos personales."/></div></Panel><Panel icon={History} title="Actividad docente" description="Próxima clase y tareas relevantes del establecimiento.">{data.nextSession?<article className="rounded-2xl border border-[var(--brand-border-soft)] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wide text-[var(--brand-secondary)]">Próxima clase</p><h3 className="mt-2 text-xl font-extrabold text-[var(--brand-ink)]">{data.nextSession.activityName}</h3><p className="mt-2 text-sm font-bold text-[var(--brand-primary)]">{data.nextSession.date} · {data.nextSession.startTime}</p><p className="mt-1 text-sm text-[var(--brand-muted)]">{data.nextSession.establishmentName} · {data.nextSession.confirmedCount} inscriptos</p></div><span className="grid size-12 place-items-center rounded-xl bg-[var(--brand-border-soft)] text-[var(--brand-primary)]"><CalendarClock/></span></div><div className="mt-5 flex flex-wrap gap-3"><Button asChild><Link href="/teacher/classes">Ver clase</Link></Button><Button asChild variant="outline"><Link href={`/teacher/attendance/${data.nextSession.id}`}>Tomar asistencia</Link></Button></div></article>:<CatalogEmptyState title="No tenés próximas clases programadas." description="Las próximas tareas docentes aparecerán en esta sección." filtered={false}/>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><SummaryItem label="Planillas pendientes" value={data.pendingRosters}/><SummaryItem label="Horarios con novedades" value={data.schedulesChanged}/></div></Panel></section></>}
function Metric({icon:Icon,label,value,subtitle}:{icon:LucideIcon;label:string;value:number;subtitle:string}){return <Card className="h-full rounded-2xl border-[var(--brand-border-soft)] bg-white shadow-sm"><CardContent className="flex h-full items-start justify-between gap-4 p-5"><div><p className="text-3xl font-extrabold text-[var(--brand-primary)]">{value}</p><p className="mt-2 font-bold text-[var(--brand-text)]">{label}</p><p className="mt-1 text-xs font-bold text-[var(--brand-secondary)]">{subtitle}</p></div><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[var(--brand-border-soft)] text-[var(--brand-primary)]"><Icon className="size-5"/></span></CardContent></Card>}
function Panel({icon,title,description,children}:{icon:LucideIcon;title:string;description:string;children:ReactNode}){return <section className="rounded-3xl border border-[var(--brand-border-soft)] bg-[var(--brand-panel)] p-5 shadow-sm sm:p-7"><AdminSectionHeader icon={icon} title={title} description={description}/><div className="mt-6">{children}</div></section>}
function QuickAction({href,icon:Icon,label,description}:{href:string;icon:LucideIcon;label:string;description:string}){return <Button asChild variant="outline" className="h-auto justify-start rounded-2xl border-[var(--brand-border-soft)] bg-white p-4 text-left hover:border-[var(--brand-secondary)] hover:bg-white"><Link href={href} className="grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--brand-border-soft)] text-[var(--brand-primary)]"><Icon className="size-5"/></span><span><span className="block font-extrabold text-[var(--brand-ink)]">{label}</span><span className="mt-1 block whitespace-normal text-xs font-medium text-[var(--brand-muted)]">{description}</span></span><ChevronRight className="size-5 text-[var(--brand-secondary)]"/></Link></Button>}
function SummaryItem({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-[var(--brand-border-soft)] bg-white p-4"><p className="text-2xl font-extrabold text-[var(--brand-primary)]">{value}</p><p className="mt-1 text-sm font-bold text-[var(--brand-muted)]">{label}</p></div>}
