/* eslint-disable react-hooks/exhaustive-deps */
"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { Building2,CalendarClock,CalendarDays,ChevronRight,History,MapPin,PauseCircle,Users } from "lucide-react";
import { AdminDetailActions,AdminDetailHeader,AdminDetailPanel,AdminListCard,AdminPageShell } from "@/components/shared/admin-patterns";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CATALOG_PAGE_SIZE,CatalogDetailField,CatalogEmptyState,CatalogFilterPopover,CatalogLoadingState,CatalogPageHeader,CatalogPagination,CatalogSearchInput,formatCatalogDate } from "@/features/activity-catalogs/components/CatalogPrimitives";
import { formatSessionDate,sessionStatusLabel } from "@/features/activity-sessions/helpers/activity-session-display";
import { ACTIVITY_SESSION_STATUSES } from "@/features/activity-sessions/schemas/activity-session.schema";
import type { ActivitySession,ActivitySessionStatus } from "@/features/activity-sessions/types/activity-session.types";
import { cn } from "@/lib/utils";
import { getTeacherClassesClient } from "../services/teacher.service";

type TimeScope="today"|"upcoming"|"recent";
type FilterSection={id:string;title:string;value:string;options:Array<{value:string;label:string}>;onChange:(value:string)=>void};

export function TeacherClassesPage(){
  const[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[page,setPage]=useState(1),[selectedId,setSelectedId]=useState(""),[items,setItems]=useState<ActivitySession[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(false),[timeScope,setTimeScope]=useState<TimeScope>("today");
  const key=useMemo(()=>JSON.stringify({search,status,page}),[search,status,page]);
  useEffect(()=>{let active=true;setLoading(true);setError(false);void getTeacherClassesClient({search:search||undefined,status:status==="all"?undefined:status as ActivitySessionStatus,page,pageSize:CATALOG_PAGE_SIZE}).then(result=>{if(active){setItems(result.data);setTotal(result.meta.total)}}).catch(()=>{if(active)setError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[key]);
  useEffect(()=>setPage(1),[search,status]);
  const selected=items.find(item=>item.id===selectedId)??items[0]??null;
  const sections:FilterSection[]=[{id:"status",title:"Estado",value:status,options:[["all","Todos"],...ACTIVITY_SESSION_STATUSES.map(item=>[item,sessionStatusLabel(item)])].map(([value,label])=>({value,label})),onChange:setStatus}];
  const mobileItems=useMemo(()=>items.filter((item)=>matchesTimeScope(item,timeScope)),[items,timeScope]);
  return <>
    <div className="md:hidden"><TeacherMobileClassesView items={mobileItems} search={search} setSearch={setSearch} status={status} page={page} setPage={setPage} selectedId={selectedId} setSelectedId={setSelectedId} total={total} loading={loading} error={error} sections={sections} timeScope={timeScope} setTimeScope={setTimeScope}/></div>
    <div className="hidden md:block"><DesktopClassesView items={items} search={search} setSearch={setSearch} status={status} page={page} setPage={setPage} selectedId={selectedId} setSelectedId={setSelectedId} selected={selected} total={total} loading={loading} error={error} sections={sections}/></div>
  </>;
}

type MobileProps={items:ActivitySession[];search:string;setSearch:(value:string)=>void;status:string;page:number;setPage:(value:number)=>void;selectedId:string;setSelectedId:(value:string)=>void;total:number;loading:boolean;error:boolean;sections:FilterSection[];timeScope:TimeScope;setTimeScope:(value:TimeScope)=>void};
function MobileTimeScopeSelector({value,onChange}:{value:TimeScope;onChange:(value:TimeScope)=>void}){
  const options=[
    {value:"today" as const,label:"Hoy",icon:CalendarDays},
    {value:"upcoming" as const,label:"Próximas",icon:CalendarClock},
    {value:"recent" as const,label:"Últimas 24 h",icon:History},
  ];
  return <div className="mt-5 grid min-w-0 grid-cols-3 gap-1.5">{options.map(({value:option,label,icon:Icon})=>{const active=value===option;return <button key={option} type="button" onClick={()=>onChange(option)} aria-pressed={active} className={cn("flex h-11 min-w-0 items-center justify-center gap-1 rounded-full border px-1.5 text-[11px] font-bold leading-none transition-colors",active?"border-[var(--brand-primary)] bg-[var(--brand-primary)] text-white shadow-sm":"border-[var(--brand-border-soft)] bg-white text-[var(--brand-primary)]")}><Icon className="size-3.5 shrink-0"/><span className="min-w-0">{label}</span></button>})}</div>;
}
function TeacherMobileClassesView({items,search,setSearch,status,page,setPage,selectedId,setSelectedId,total,loading,error,sections,timeScope,setTimeScope}:MobileProps){return <main className="min-h-full bg-[var(--brand-page)] px-4 py-5"><header><div className="flex items-center justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-[var(--brand-primary)]">Mis clases</h1><p className="mt-1 text-sm leading-5 text-[var(--brand-muted)]">Consultá tus clases asignadas, próximas y recientes.</p></div><span className="grid min-w-9 place-items-center rounded-full bg-[var(--brand-primary)] px-2 py-1 text-xs font-bold text-white">{total}</span></div></header><MobileTimeScopeSelector value={timeScope} onChange={setTimeScope}/><div className="mt-3 grid grid-cols-[minmax(0,1fr)_auto] gap-2"><CatalogSearchInput value={search} onChange={setSearch} placeholder="Buscar clases..."/><CatalogFilterPopover sections={sections}/></div>{loading?<div className="mt-4"><CatalogLoadingState label="clases"/></div>:error?<div className="mt-4"><CatalogEmptyState title="No pudimos cargar las clases." description="Reintentá nuevamente en unos instantes." filtered={false}/></div>:!items.length?<div className="mt-4"><CatalogEmptyState title="No se encontraron clases." description="No tenés clases para este período y filtros." filtered={Boolean(search||status!=="all")}/></div>:<div className="mt-4 grid gap-3">{items.map((item)=><TeacherMobileClassCard key={item.id} item={item} open={selectedId===item.id} onToggle={()=>setSelectedId(selectedId===item.id?"":item.id)}/>)}</div>}<div className="mt-4"><CatalogPagination page={page} total={total} onPageChange={setPage}/></div></main>}

function TeacherMobileClassCard({item}:{item:ActivitySession;open:boolean;onToggle:()=>void}){return <Link href={`/teacher/classes/${item.id}`} className="grid min-w-0 grid-cols-[auto_minmax(0,1fr)_auto] items-start gap-3 rounded-2xl border border-[var(--brand-border-soft)] bg-[#F9FAF5] p-3 text-left shadow-sm"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-[var(--brand-primary)] text-white"><CalendarDays className="size-6"/></span><span className="min-w-0"><span className="block break-words text-sm font-extrabold leading-5 text-[var(--brand-ink)]">{item.activitySchedule.activity.name}</span><span className="mt-1 block break-words text-xs leading-4 text-[var(--brand-muted)]">{item.establishment.name}{item.space?` · ${item.space}`:""}</span><span className="mt-1 block text-[11px] font-bold leading-4 text-[var(--brand-primary)]">{formatSessionDate(item.date)} · {item.startTime} a {item.endTime}</span></span><span className="flex min-w-0 flex-col items-end gap-2"><State value={item.status}/><ChevronRight className="size-4 text-[var(--brand-secondary)]"/></span></Link>}

type DesktopProps={items:ActivitySession[];search:string;setSearch:(value:string)=>void;status:string;page:number;setPage:(value:number)=>void;selectedId:string;setSelectedId:(value:string)=>void;selected:ActivitySession|null;total:number;loading:boolean;error:boolean;sections:FilterSection[]};
function DesktopClassesView({items,search,setSearch,status,page,setPage,selectedId,setSelectedId,selected,total,loading,error,sections}:DesktopProps){return <AdminPageShell><CatalogPageHeader icon={CalendarDays} title="Clases" description="Consultá las clases en las que estás asignado como profesor." total={total}/><section className="mt-6 grid min-h-0 gap-6 lg:grid-cols-[minmax(340px,.95fr)_minmax(420px,1.05fr)]"><div className={cn("min-h-0 flex-col gap-4",selectedId?"hidden lg:flex":"flex")}><div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><CatalogSearchInput value={search} onChange={setSearch} placeholder="Buscar actividad, sede, espacio o profesor..."/><CatalogFilterPopover sections={sections}/></div>{loading?<CatalogLoadingState label="clases"/>:error?<CatalogEmptyState title="No pudimos cargar las clases." description="Reintentá nuevamente en unos instantes." filtered={false}/>:!items.length?<CatalogEmptyState title="No se encontraron clases." description="No tenés clases recientes ni próximas en este establecimiento." filtered={Boolean(search||status!=="all")}/>:<div className="flex min-h-0 flex-col gap-3"><div className="grid gap-3 overflow-y-auto pr-1 lg:max-h-[calc(100dvh-var(--topbar-h)-300px)]">{items.map(item=><AdminListCard key={item.id} onClick={()=>setSelectedId(item.id)} selected={selected?.id===item.id} leading={<span className="grid size-12 place-items-center rounded-xl bg-[var(--brand-primary)] text-white"><CalendarDays/></span>} title={item.activitySchedule.activity.name} badges={<State value={item.status}/>} description={<span className="flex items-center gap-1"><MapPin className="size-3.5"/>{item.establishment.name}{item.space?` · ${item.space}`:""}</span>} meta={`${formatSessionDate(item.date)} · ${item.startTime} a ${item.endTime}`} trailing={<ChevronRight/>}/>)}</div><CatalogPagination page={page} total={total} onPageChange={setPage}/></div>}</div><div className={cn(!selectedId&&"hidden lg:block")}><Detail item={selected} onBack={()=>setSelectedId("")}/></div></section></AdminPageShell>}

function matchesTimeScope(item:ActivitySession,scope:TimeScope){const now=new Date(),today=localDateKey(now),itemDate=item.date.slice(0,10);if(scope==="today")return itemDate===today;if(scope==="upcoming")return itemDate>today;const end=new Date(`${itemDate}T${item.endTime.length===5?`${item.endTime}:00`:item.endTime}`);return end.getTime()<=now.getTime()&&end.getTime()>=now.getTime()-24*60*60*1000}
function localDateKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function Detail({item,onBack}:{item:ActivitySession|null;onBack:()=>void}){if(!item)return <AdminDetailPanel empty="Seleccioná una clase para consultar su detalle."/>;const suspendAllowed=["PROGRAMADA","EN_CURSO"].includes(item.status);return <AdminDetailPanel onBack={onBack}><AdminDetailHeader title={item.activitySchedule.activity.name} subtitle={`${formatSessionDate(item.date)} · ${item.startTime} a ${item.endTime}`} leading={<span className="grid size-16 place-items-center rounded-2xl bg-[var(--brand-primary)] text-white"><CalendarDays className="size-8"/></span>} badge={<State value={item.status}/>}/><dl className="mt-6 grid gap-3"><CatalogDetailField icon={CalendarClock} label="Fecha y hora">{formatSessionDate(item.date)} · {item.startTime} a {item.endTime}</CatalogDetailField><CatalogDetailField icon={Building2} label="Establecimiento">{item.establishment.name} · {item.establishment.address}</CatalogDetailField><CatalogDetailField icon={MapPin} label="Espacio">{item.space||"Sin informar"}</CatalogDetailField><CatalogDetailField icon={Users} label="Profesores">{item.professors.map(p=>`${p.fullName}${p.isPrimary?" (principal)":" (adicional)"}`).join(", ")||"Sin profesores"}</CatalogDetailField><CatalogDetailField icon={Users} label="Participación">{item.enrollmentSummary.confirmedCount} confirmados · {item.enrollmentSummary.waitlistCount} en espera</CatalogDetailField><CatalogDetailField icon={CalendarClock} label="Registro">Creada {formatCatalogDate(item.createdAt)} · Actualizada {formatCatalogDate(item.updatedAt)}</CatalogDetailField></dl>{suspendAllowed?<AdminDetailActions><Button asChild variant="outline"><Link href={`/teacher/classes/${item.id}/suspend`}><PauseCircle/>Suspender</Link></Button></AdminDetailActions>:null}</AdminDetailPanel>}
function State({value}:{value:ActivitySessionStatus}){return <Badge variant="outline" className="h-6 max-w-[88px] rounded-full border-[var(--brand-secondary)]/40 bg-[var(--brand-secondary)]/15 px-2 py-0 text-[9px] font-bold text-[var(--brand-primary)] md:h-auto md:max-w-none md:px-2.5 md:py-1 md:text-xs">{sessionStatusLabel(value)}</Badge>}
