"use client";

import Link from "next/link";
import { Bell, Building2, CalendarClock, CalendarDays, ChevronDown, ChevronRight, ClipboardCheck, Clock3, MapPin, UserRound, Zap, type LucideIcon } from "lucide-react";
import { ActivityImagePreview } from "@/features/actividades/components/ActivityImagePreview";
import { UserAvatar } from "@/components/layout/user-menu/UserAvatar";
import { useAuth } from "@/stores/auth";
import type { TeacherSummary, TeacherSummarySession } from "../TeacherDashboard";
import { useTeacherEstablishment } from "../../hooks/useTeacherEstablishment";

const quickActions: Array<{href:string;label:string;icon:LucideIcon}> = [
  {href:"/teacher/classes",label:"Ver clases",icon:CalendarDays},
  {href:"/teacher/attendance",label:"Tomar asistencia",icon:ClipboardCheck},
  {href:"/teacher/schedules",label:"Horarios",icon:Clock3},
  {href:"/teacher/notifications",label:"Notificaciones",icon:Bell},
  {href:"/teacher/profile",label:"Mi perfil",icon:UserRound},
];

export function TeacherMobileDashboard({data}:{data:TeacherSummary}) {
  const user=useAuth((state)=>state.user);
  const establishmentContext=useTeacherEstablishment();
  const establishment=establishmentContext.establishments.find((item)=>item.id===establishmentContext.establishmentId);
  const fullName=[user?.nombre,user?.apellido].filter(Boolean).join(" ")||user?.userId||"Profesor";
  const firstName=user?.nombre||"Profesor";
  return <div className="min-h-full overflow-x-hidden bg-[var(--brand-page)] pb-5">
    <section className="grid gap-3 px-4 py-5 min-[390px]:grid-cols-[minmax(0,1fr)_minmax(145px,.9fr)] min-[390px]:items-center"><div className="flex min-w-0 items-center gap-3"><UserAvatar src={user?.avatarUrl??undefined} name={fullName} className="size-14 shrink-0 rounded-full border-2 border-white shadow-md ring-1 ring-[var(--brand-border-soft)]" imageClassName="size-full rounded-full object-cover" fallbackBgClass="rounded-full bg-[var(--brand-panel)]" textClass="font-extrabold text-[var(--brand-primary)]"/><div className="min-w-0"><h1 className="truncate text-xl font-extrabold text-[var(--brand-primary)]">Hola, {firstName}</h1><Link href="/select-venue?workspace=teacher&next=%2Fteacher" className="mt-1 flex min-w-0 items-center gap-1 text-xs text-[var(--brand-ink)]"><MapPin className="size-4 shrink-0 text-[var(--brand-primary)]"/><span className="truncate">{establishment?.nombre||"Seleccionar establecimiento"}</span><ChevronDown className="size-4 shrink-0"/></Link></div></div><Link href="/select-venue?workspace=teacher&next=%2Fteacher" className="flex min-w-0 items-center gap-2.5 rounded-2xl border border-[var(--brand-border-soft)] bg-white p-3 shadow-sm"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[var(--brand-primary)] text-white"><Building2 className="size-5"/></span><span className="min-w-0 flex-1"><span className="block text-[9px] font-bold text-[var(--brand-primary)]">Establecimiento elegido</span><strong className="mt-1 block truncate text-xs text-[var(--brand-ink)]">{establishment?.nombre||"Seleccionar"}</strong><span className="mt-0.5 block truncate text-[10px] text-[var(--brand-muted)]">{establishment?.direccion||"Dirección no informada"}</span></span><ChevronRight className="size-4 shrink-0 text-[var(--brand-secondary)]"/></Link></section>

    <section className="grid grid-cols-3 gap-2 px-4"><Metric icon={CalendarDays} label="Clases de hoy" value={data.todaySessions} href="/teacher/classes"/><Metric icon={CalendarClock} label="Próximas clases" value={data.upcomingSessions} href="/teacher/classes"/><Metric icon={ClipboardCheck} label="Pendientes" value={data.pendingRosters} href="/teacher/attendance"/></section>

    <section className="mt-6"><h2 className="mb-3 flex items-center gap-2 px-4 font-extrabold text-[var(--brand-primary)]"><Zap className="size-5 fill-current"/>Acciones rápidas</h2><div className="grid grid-cols-5 gap-2 px-4">{quickActions.map(({href,label,icon:Icon})=><Link key={href} href={href} className="flex min-h-24 min-w-0 flex-col items-center justify-center rounded-2xl border border-[var(--brand-border-soft)] bg-[#F9FAF5] px-1 py-2 text-center text-[9px] font-bold leading-3 text-[var(--brand-ink)] shadow-sm"><span className="mb-2 grid size-8 place-items-center text-[var(--brand-primary)]"><Icon className="size-6"/></span>{label}</Link>)}</div></section>

    <section className="mt-6 grid grid-cols-2 items-stretch gap-3 px-4">
      <NextClass session={data.nextSession}/>
      <TodayClasses sessions={data.todayClasses}/>
    </section>
  </div>;
}

function Metric({icon:Icon,label,value,href}:{icon:LucideIcon;label:string;value:number;href:string}){return <Link href={href} className="flex min-h-24 min-w-0 flex-col rounded-2xl border border-[var(--brand-border-soft)] bg-[#F9FAF5] p-2.5 shadow-[0_8px_20px_rgba(29,79,54,0.12)]"><span className="text-[12px] font-extrabold leading-[14px] text-[var(--brand-ink)]">{label}</span><span className="mt-auto flex items-end justify-between gap-1"><span className="grid size-8 shrink-0 place-items-center rounded-xl bg-[var(--brand-panel)] text-[var(--brand-primary)]"><Icon className="size-4.5"/></span><strong className="text-3xl leading-none text-[var(--brand-primary)]">{value}</strong></span></Link>}

function NextClass({session}:{session:TeacherSummarySession|null}){return <article className="relative min-h-[268px] min-w-0 overflow-hidden rounded-3xl border border-[var(--brand-border-soft)] bg-[#F9FAF5] p-3 shadow-sm"><span aria-hidden className="absolute -bottom-5 -left-8 size-32 rounded-full bg-[#DCEFD5]/80"/><span aria-hidden className="absolute bottom-10 right-[-38px] size-36 rounded-full bg-[#DCEFD5]/75"/><span aria-hidden className="absolute bottom-1 right-14 size-20 rounded-full bg-[#CDE7C5]/60"/><div className="relative z-10"><p className="inline-flex rounded-md bg-[#E8F4E5] px-2 py-1 text-[9px] font-extrabold uppercase text-[var(--brand-primary)]">Próxima clase</p>{session?<><div className="mt-3 max-w-[78%]"><h2 className="text-base font-extrabold leading-5 text-[var(--brand-primary)]">{session.activityName}</h2><div className="mt-3 space-y-2 text-[10px] leading-4 text-[var(--brand-text)]"><p className="flex items-start gap-1.5"><CalendarClock className="mt-0.5 size-3.5 shrink-0"/>{formatDate(session.date)} · {session.startTime}</p><p className="flex items-start gap-1.5"><MapPin className="mt-0.5 size-3.5 shrink-0"/><span>{session.establishmentName}{session.space?` · ${session.space}`:""}</span></p><p>{session.confirmedCount} participantes</p></div></div><Link href={`/teacher/sessions/${session.id}`} className="relative z-20 mt-4 inline-flex h-10 w-[76px] items-center justify-between rounded-xl border border-[var(--brand-primary)] bg-white/40 px-2.5 text-[10px] font-bold leading-none text-[var(--brand-primary)]"><span className="text-left leading-[1.05]"><span className="block">Ver</span><span className="block">detalles</span></span><ChevronRight aria-hidden="true" className="size-3.5 shrink-0"/></Link><ActivityImagePreview source={session.activityImageUrl} alt={`Imagen de ${session.activityName}`} className="absolute bottom-0 right-0 z-10 size-16 !border-0 !bg-transparent object-contain"/></>:<div className="grid min-h-[200px] place-items-center text-center"><div><CalendarClock className="mx-auto size-9 text-[var(--brand-secondary)]"/><p className="mt-3 text-xs font-bold text-[var(--brand-muted)]">No tenés próximas clases programadas.</p></div></div>}</div></article>}

function TodayClasses({sessions}:{sessions:TeacherSummarySession[]}){return <article className="min-h-[268px] rounded-3xl border border-[var(--brand-border-soft)] bg-[#F9FAF5] p-3 shadow-sm"><div className="flex items-center justify-between gap-2"><h2 className="text-[10px] font-extrabold uppercase leading-3 text-[var(--brand-primary)]">Mis clases de hoy</h2><span className="grid min-w-6 place-items-center rounded-full bg-[var(--brand-primary)] px-1.5 py-1 text-[10px] font-bold text-white">{sessions.length}</span></div><div className="mt-2 divide-y divide-[var(--brand-border-soft)]">{sessions.length?sessions.slice(0,3).map((session)=><Link key={session.id} href={`/teacher/sessions/${session.id}`} className="flex items-start gap-1.5 py-2"><span className="grid size-7 shrink-0 place-items-center rounded-xl bg-[var(--brand-panel)] text-[var(--brand-primary)]"><CalendarDays className="size-3.5"/></span><span className="min-w-0 flex-1"><span className="flex items-start justify-between gap-1"><span className="truncate text-[10px] font-bold text-[var(--brand-ink)]">{session.activityName}</span><span className="shrink-0 rounded-full border border-[var(--brand-border-soft)] bg-white px-1 py-0.5 text-[7px] font-bold text-[var(--brand-primary)]">{statusLabel(session.status)}</span></span><span className="block text-[9px] leading-3 text-[var(--brand-muted)]">{session.startTime}–{session.endTime}</span><span className="block truncate text-[9px] leading-3 text-[var(--brand-muted)]">{session.establishmentName}</span></span></Link>):<p className="py-8 text-center text-xs text-[var(--brand-muted)]">No tenés clases para hoy.</p>}</div><Link href="/teacher/classes" className="mt-2 flex items-center justify-between text-[10px] font-bold text-[var(--brand-primary)]">Ver todas mis clases <ChevronRight className="size-3.5"/></Link></article>}

function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(date)}
function statusLabel(value:string){return value.replaceAll("_"," ").toLocaleLowerCase("es-AR")}
