import assert from "node:assert/strict";
import { NextRequest } from "next/server";
import { GET as list, POST as create } from "../src/app/api/attendance/route";
import { GET as roster, PATCH as update } from "../src/app/api/attendance/[id]/route";
import { POST as batch } from "../src/app/api/attendance/batch/route";
import { POST as close } from "../src/app/api/attendance/close/route";
import { POST as reopen } from "../src/app/api/attendance/reopen/route";
import { prisma } from "../src/lib/db";
import { signJwt } from "../src/lib/jwt";
const marker=`TEST_ATTENDANCE_RBAC_${Date.now()}`,roles:number[]=[],users:string[]=[];
function request(path:string,token:string,method="GET",body?:unknown){return new NextRequest(`http://localhost/api${path}`,{method,headers:{authorization:`Bearer ${token}`,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined})}
async function expect403(label:string,response:Response){assert.equal(response.status,403,`${label}: ${response.status} ${await response.text()}`);console.log(`${label}: 403`)}
async function tokenMissing(action:string,permissions:{id:number;accion:string}[]){const role=await prisma.rol.create({data:{nombre:`${marker}_${action}`,descripcion:"Temporal RBAC"}});roles.push(role.id);await prisma.rolPermiso.createMany({data:permissions.filter(x=>x.accion!==action).map(x=>({rolId:role.id,permisoId:x.id}))});const user=await prisma.usuario.create({data:{userId:`${marker}_${action}`,email:`${marker}_${action}@test.local`,nombre:"Operador",apellido:"Temporal",rolId:role.id,estado:"ACTIVO"}});users.push(user.id);return signJwt({uid:user.id,rid:role.id},"15m")}
async function main(){const before={roles:await prisma.rol.count(),users:await prisma.usuario.count(),links:await prisma.rolPermiso.count()};try{const permissions=await prisma.permiso.findMany({where:{modulo:"attendance"},select:{id:true,accion:true}});assert.equal(permissions.length,5);const noView=await tokenMissing("ver",permissions),noCreate=await tokenMissing("crear",permissions),noEdit=await tokenMissing("editar",permissions),noAssign=await tokenMissing("asignar",permissions),noDelete=await tokenMissing("eliminar",permissions);await expect403("GET listado sin ver",await list(request("/attendance",noView)));await expect403("GET listado userId sin ver",await list(request("/attendance?userId=00000000-0000-0000-0000-000000000000",noView)));await expect403("GET roster sin ver",await roster(request("/attendance/fake",noView),{params:Promise.resolve({id:"fake"})}));await expect403("POST individual sin crear",await create(request("/attendance",noCreate,"POST",{})));await expect403("PATCH sin editar",await update(request("/attendance/fake",noEdit,"PATCH",{}),{params:Promise.resolve({id:"fake"})}));await expect403("POST batch sin asignar",await batch(request("/attendance/batch",noAssign,"POST",{})));await expect403("POST cierre sin asignar",await close(request("/attendance/close",noAssign,"POST",{})));await expect403("POST reapertura sin eliminar",await reopen(request("/attendance/reopen",noDelete,"POST",{})));console.log(JSON.stringify({ok:true,before}));}finally{if(users.length)await prisma.usuario.deleteMany({where:{id:{in:users}}});if(roles.length)await prisma.rolPermiso.deleteMany({where:{rolId:{in:roles}}});if(roles.length)await prisma.rol.deleteMany({where:{id:{in:roles}}});const after={roles:await prisma.rol.count(),users:await prisma.usuario.count(),links:await prisma.rolPermiso.count()};console.log(JSON.stringify({cleanup:true,after}));await prisma.$disconnect()}}
main();
