"use client";
import { useMemo, useState } from "react";
import { Check, Info, Search } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { CatalogEmptyState } from "@/features/activity-catalogs/components/CatalogPrimitives";
import { cn } from "@/lib/utils";

export type WorkflowSelectionOption = { id: string; title: string; subtitle?: string | null; description?: string | null; meta?: string | null };
export function WorkflowSelectionBrowser({ options, selectedIds, onToggle, searchPlaceholder, emptyTitle }: { options: WorkflowSelectionOption[]; selectedIds: string[]; onToggle: (id: string, checked: boolean) => void; searchPlaceholder: string; emptyTitle: string }) {
  const [query, setQuery] = useState("");
  const [activeId, setActiveId] = useState<string | null>(selectedIds[0] ?? options[0]?.id ?? null);
  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); return value ? options.filter((item) => `${item.title} ${item.subtitle ?? ""} ${item.description ?? ""}`.toLowerCase().includes(value)) : options; }, [options, query]);
  const active = options.find((item) => item.id === activeId) ?? filtered[0] ?? null;
  return <div className="grid gap-5 lg:grid-cols-[minmax(0,.95fr)_minmax(320px,1.05fr)]"><div className="space-y-3"><div className="relative"><Search className="pointer-events-none absolute left-4 top-3.5 size-5 text-[#1D4F36]" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={searchPlaceholder} className="h-12 rounded-xl border-0 bg-[var(--brand-search)] pl-12 font-medium shadow-sm" /></div>{!filtered.length ? <CatalogEmptyState title={emptyTitle} description="Probá con otro término de búsqueda." filtered={Boolean(query)} /> : <div className="grid max-h-[430px] gap-3 overflow-y-auto pr-1">{filtered.map((item) => { const checked = selectedIds.includes(item.id); return <button type="button" key={item.id} onClick={() => setActiveId(item.id)} className={cn("flex items-start gap-3 rounded-2xl border p-4 text-left transition", active?.id === item.id ? "border-[#819B56] bg-[#EEF6E9]" : "border-[#DDE8D7] bg-white hover:border-[#819B56]")}><Checkbox checked={checked} onCheckedChange={(value) => onToggle(item.id, value === true)} onClick={(event) => event.stopPropagation()} /><span className="min-w-0 flex-1"><span className="block font-extrabold text-[#1D4F36]">{item.title}</span>{item.subtitle ? <span className="mt-1 block text-sm text-[#5F6F68]">{item.subtitle}</span> : null}</span>{checked ? <Check className="size-5 shrink-0 text-[#1D4F36]" /> : null}</button>; })}</div>}</div><div className="h-fit rounded-3xl border border-[#DDE8D7] bg-[#F7FBF5] p-6">{active ? <><div className="flex items-start gap-3 border-b border-[#C9D9C3] pb-4"><span className="grid size-11 place-items-center rounded-xl bg-[#DDE8D7] text-[#1D4F36]"><Info className="size-5" /></span><div><h3 className="text-xl font-extrabold text-[#1D4F36]">{active.title}</h3>{active.subtitle ? <p className="mt-1 text-sm font-medium text-[#315644]">{active.subtitle}</p> : null}</div></div><p className="mt-5 whitespace-pre-line text-sm leading-6 text-[#5F6F68]">{active.description || "No se cargó una descripción para esta opción."}</p>{active.meta ? <p className="mt-4 rounded-xl bg-white p-3 text-sm font-bold text-[#315644]">{active.meta}</p> : null}</> : <p className="text-sm text-[#5F6F68]">Seleccioná una opción para consultar su descripción.</p>}</div></div>;
}
