import { NextRequest,NextResponse } from "next/server";
import { getAuditRequestContext } from "@/features/audit-log/helpers/audit-log.helpers";
import { createAuditLog } from "@/features/audit-log/services/audit-log.server";
import { createNotificationSchema } from "@/features/notifications/schemas/notification.schema";
import { createNotification,ensurePendingAccessRequestNotifications,listNotifications } from "@/features/notifications/services/notifications.server";
import { mapApiRouteError } from "@/lib/api/route-error";
import { requireAuth,requirePermission } from "@/lib/server-auth";
export async function GET(req:NextRequest){try{const user=await requireAuth(req);requirePermission(user,"notifications","ver");if(user.rol?.codigo==="admin")await ensurePendingAccessRequestNotifications();return NextResponse.json({data:await listNotifications({...Object.fromEntries(req.nextUrl.searchParams),userId:user.id})});}catch(error){return mapApiRouteError(error,"No pudimos cargar notificaciones.");}}
export async function POST(req:NextRequest){try{const user=await requireAuth(req);requirePermission(user,"notifications","crear");requirePermission(user,"notifications","asignar");const parsed=createNotificationSchema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({message:"Datos inválidos",details:parsed.error.flatten()},{status:400});const data=await createNotification({userId:parsed.data.userId,senderId:user.id,type:"GENERAL",title:parsed.data.title,message:parsed.data.message,priority:parsed.data.priority,actionUrl:parsed.data.actionUrl,actionLabel:parsed.data.actionLabel});await createAuditLog({actorId:user.id,action:"CREAR",entityType:"NOTIFICACION",entityId:data.id,entityName:data.title,metadata:{recipientId:parsed.data.userId},origin:"ADMINISTRACION",requestContext:getAuditRequestContext(req.headers)});return NextResponse.json({data},{status:201});}catch(error){return mapApiRouteError(error,"No pudimos crear la notificación.");}}
