import { z } from "zod";

export const ENROLLMENT_STATUSES = ["PENDIENTE", "CONFIRMADA", "LISTA_ESPERA", "CANCELADA", "RECHAZADA", "BAJA"] as const;
export const createEnrollmentSchema = z.object({ usuarioId: z.string().uuid(), actividadId: z.string().min(1).optional(), horarioActividadId: z.string().min(1).optional(), horarioActividadIds: z.array(z.string().min(1)).max(20).optional(), horariosSeleccionados: z.array(z.object({ horarioActividadId:z.string().min(1), horaInicio:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), horaFin:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/) })).max(30).optional(), claseActividadId: z.string().min(1).optional(), fechaFin: z.coerce.date().nullable().optional(), observaciones: z.string().trim().max(1000).nullable().optional(), nivelConsentido: z.boolean().optional() }).superRefine((value, context) => {
  if (!value.actividadId && !value.horarioActividadId) context.addIssue({ code: "custom", path: ["actividadId"], message: "Seleccioná una actividad." });
  if (value.horarioActividadIds && new Set(value.horarioActividadIds).size !== value.horarioActividadIds.length) context.addIssue({ code: "custom", path: ["horarioActividadIds"], message: "No repitas horarios." });
});
const patch = z.object({ observaciones: z.string().trim().max(1000).nullable().optional(), estado: z.enum(ENROLLMENT_STATUSES).optional(), motivoRechazo: z.string().trim().max(500).nullable().optional(), motivoCancelacion: z.string().trim().max(500).nullable().optional() });
export const updateEnrollmentSchema = z.object({}).passthrough().refine((value) => Object.keys(value).length > 0, "No se informaron cambios").pipe(patch).superRefine((value, context) => { if (value.estado === "RECHAZADA" && !value.motivoRechazo?.trim()) context.addIssue({ code:"custom",path:["motivoRechazo"],message:"Indicá el motivo del rechazo" }); });
export const enrollmentFiltersSchema = z.object({ search:z.string().optional(),status:z.enum(ENROLLMENT_STATUSES).optional(),userId:z.string().uuid().optional(),activityId:z.string().optional(),activityScheduleId:z.string().optional(),establishmentId:z.string().optional(),professorId:z.string().uuid().optional(),day:z.string().optional(),dateFrom:z.coerce.date().optional(),dateTo:z.coerce.date().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(8),sortBy:z.enum(["enrollmentDate","user","activity","status","updatedAt"]).default("enrollmentDate"),sortDir:z.enum(["asc","desc"]).default("desc") });
